### ISSUE TITLE
 whatsapp messages

### ISSUE THREAD

**Issue by pkay22** [loqui/im#1118] opened 2016-07-25 08:49 UTC
I can't scroll up and down my whatsapp messages

**Comment by pkay22** [comment] 2016-07-29 09:21
Please help me out my version of loqui is 0.5.7a

**Comment by petermalcom** [comment] 2016-07-30 11:19
I can't see chats

**Comment by cmeerw** [comment] 2016-08-01 16:18
likely duplicate of #910

**Closed as completed by cmeerw** 2016-08-01 16:18 UTC
