### ISSUE TITLE
Can't log in to Google Hangouts account

### ISSUE THREAD

**Issue by soapdog** [loqui/im#360] opened 2014-03-21 20:19 UTC
Hey Folks,

I can't log in to Google Hangouts from a Google Apps account. My hangout account is under my own domain email. On loqui it keeps saying there is an authentication failure but it works fine on the desktop.

cheers

**Comment by Gioyik** [comment] 2014-03-23 18:11
Strophe uses PLAIN-AUTH for XMPP connections. So, it let connect only main domain accouns (gmail.com). We are working on a fix for this implementing OAuth. 

Thanks for the report

**Comment by aesedepece** [comment] 2014-05-02 10:16
Duplicate of #79. Let's track it there.

**Closed as completed by aesedepece** 2014-05-02 10:16 UTC
Labels: enhancement, JS, P1, Important!
