### ISSUE TITLE
when creating a WhatsApp group I am no admin...

### ISSUE THREAD

**Issue by boom0815** [loqui/im#795] opened 2015-08-31 15:26 UTC
I created a group in WhatsApp but I am no admin... which means I cannot change the group chat Picture or delete the whole thing up

or is it a feature... :-)

**Comment by cmeerw** [comment] 2015-08-31 15:36
well, it's a missing feature, it's essentially a duplicate of #517

**Closed as completed by cmeerw** 2015-08-31 15:36 UTC
