### ISSUE TITLE
[WhatsApp] Messages not displayed

### ISSUE THREAD

**Issue by Giammy86** [loqui/im#608] opened 2014-12-13 10:43 UTC
While I receive perfectly messages from whatsapp groups when someone sends me messages privately on whatsapp i receive sound notification and and new messages green dot notification but no message can be read.

**Comment by TitanNano** [comment] 2014-12-13 13:28
This sounds like a duplicate of #598. Do you receive this messages from an android client?

**Comment by Giammy86** [comment] 2014-12-13 17:37
Yes haven't tried from iOS client.

**Comment by TitanNano** [comment] 2014-12-13 17:37
okay, then it is a duplicate of #598

**Closed as completed** 2014-12-13 17:38 UTC
Labels: duplicate
