### ISSUE TITLE
[WhatsApp] refresh contacts button not works

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#255] opened 2014-01-20 21:05 UTC
0.2.4 on GP Peak, B2G 1.1.1.0hd-GP (stable).

Whatsapp refresh contacts button looks like not been clickable (as there is no indication on/after click) or just not works (as the list still show many deleted on the phone contacts).

**Comment by Gioyik** [comment] 2014-01-21 01:25
Yes, this is solved, see #174. But I am going to test it again, because I was seeing that on production devices using the latest on master the button is not working, maybe, we have other CSP violation.

**Comment by Gioyik** [comment] 2014-01-21 01:48
I can't see any CSP violation in logcat, in the validator important violations are not showed.

https://marketplace.firefox.com/developers/upload/7dd7aa69f199447fb9d557d076511163

**Comment by bdcomp** [comment] 2014-01-21 06:10
If so, I will retest this issue on v0.2.5

**Comment by aarizkuren** [comment] 2014-01-24 23:29
Tested on 0.2.5 GP Keon, and works correctly, with B2G 1.4.0.0-prerelease
@bdcomp can you say us your testing results ? thx!

**Comment by aesedepece** [comment] 2014-01-25 04:05
Maybe you denied "contacts" permission to Loqui and so now it can't sync to your address book.
Just in case: please check it under the "App permissions" menu in your phone's Settings app.

**Comment by Gioyik** [comment] 2014-01-25 04:13
I tested onnAlcatel phone and the same problem here. The thing is that the console doesn't shows nothing related to the error and the logcat doesn't shows CSP violation that could block the JavaScript.

**Comment by aesedepece** [comment] 2014-01-25 04:14
Maybe has something to do with the B2G version? We have seen API inconsistencies between versions before...

**Comment by Gioyik** [comment] 2014-01-25 04:19
Maybe, but the problem is on the reload icon button. The contacts are well synchronized but the button is the one that didn't work.

**Comment by aesedepece** [comment] 2014-01-25 13:16
Ok, so I think this is what's going on:
- _«there is no indication on/after click»_ → The "Syncing" notification is not being shown (in fact is shown and hidden after only a few milliseconds). I suppose we have to check the `Lungo.Notification.show()` is being called at the correct point.
- _«the list still show many deleted on the phone contacts»_ → The `.sync()` is very conservative at the moment and doesn't wipe your contacts list before the syncing, it just adds new contacts or update modified ones.

**Comment by bdcomp** [comment] 2014-01-25 16:01
@aarizkuren I am not sure how I can test the unreleased v0.2.5 ...

@aesedepece Under the "App permissions" it's allowed.

**Comment by bdcomp** [comment] 2014-01-27 19:02
Well, just tested this on v0.2.5 and it's still exactly as described originally.

P.S. The console doesn't show anything after clicking the refresh button. Should it?

**Comment by Gioyik** [comment] 2014-01-27 19:08
It must show a notification per 3 seconds mentioning that the contact list is reloading.

**Comment by aesedepece** [comment] 2014-01-27 19:09
I explained what the bug is: the library we are using doesn't recognize numbers from Brazil, but we have yet to decide the change to another library.

**Comment by bdcomp** [comment] 2014-01-27 19:17
@Gioyik No notification at all, not in console, nor on the screen.

@aesedepece How Brazil related while I am from Israel? :)

**Comment by aesedepece** [comment] 2014-01-27 19:24
@bdcomp Sorry, mixed two different issues in my mind.

Anyway, are new contacts being imported at all?

**Comment by bdcomp** [comment] 2014-01-27 19:28
No, new contacts not imported.
Deleted on the phone contacts not removed as well.

**Comment by aesedepece** [comment] 2014-01-27 19:31
I insist: deleted numbers were not supposed to be removed upon sync. We could change this in the future if it's not convenient for most users.

**Comment by bdcomp** [comment] 2014-01-27 19:46
If "deleted numbers were not supposed to be removed upon sync" by design, let stick here to the import and update of contacts.
How I can help to debug this?

**Comment by woodymonk** [comment] 2014-01-27 20:19
Updated to 0.2.5, tried the refresh contacts button, is that the one right of the search box? Firstly its pretty small for my fingers and it thinks I'm clicking the scroll bar. Secondly it doesn't do anything besides that. No new contacts are imported.
Using a ZTE Open with F.OS 1.2

**Comment by woodymonk** [comment] 2014-01-29 12:18
Same issue with 0.2.5b, no new contacts are loaded, after they are added to the F.OS contact list.

**Comment by aesedepece** [comment] 2014-01-29 14:17
I'm quite sure the problem comes from the number validation process inside the `sync()` function.

Can you check if some of your contacts numbers pass against each one of this test?
[1]  http://logofid.es/phonenumberjs_test/
[2]  http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html

Another question: what format do you usually store your contacts numbers in?
- 52 123 4567
- 052 123 4567
- 972 52 123 4567
- 972 052 123 4567

Thanks in advance for the information.

**Comment by woodymonk** [comment] 2014-01-29 14:30
All my numbers are stored in one of the following formats:
- 0612345678
- +31612345678

Both being mobile NL numbers. They check out fine with both those tests. What's funny that the first time I installed LoquiIM it imported all contacts correctly. Then I added a few in the same way (using Google Accounts sync) to the F.OS contacts, and they don't show up when I click the refresh button. Actually nothing happens at all, not even a notice its trying to synchronize.

**Comment by bdcomp** [comment] 2014-01-29 15:41
Most of my contacts are in these formats:
052 123 4567
03 123 4567

**Comment by pavi** [comment] 2014-01-31 03:20
Is there support for international style , I am not sure if its a standard or not http://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_listing_by_country_or_region 

Anyways most of the phones I used had this +countrycode folowed by local number , sometimes the local no would have a zero before the no when used locally .

**Comment by aesedepece** [comment] 2014-01-31 03:24
@pavi The new library we are testing has succeeded validating every number and format we've seen so far, and it even takes into account the leading zeroes and repeated country codes :wink:

**Comment by Gioyik** [comment] 2014-01-31 14:56
This is solved after PR merged.

**Comment by bdcomp** [comment] 2014-02-18 19:50
@Gioyik @aesedepece 
I just retested this on v0.2.6 on GP Peak, B2G 1.1.1.0hd-GP (stable), and it still exactly as originally described - sync can't be clicked or do nothing.

Please reopen this issue.

**Comment by aesedepece** [comment] 2014-02-18 20:00
Misterious...

**Comment by TitanNano** [comment] 2014-11-19 16:19
The button works for me perfectly fine on 2.1 and also did on 2.0 and 1.4. Is this still relevant?

**Closed as completed** 2015-02-08 16:29 UTC
Labels: bug, unconfirmed, UX
