### ISSUE TITLE
messages only displayed in the preview

### ISSUE THREAD

**Issue by tibtab** [loqui/im#719] opened 2015-05-19 20:06 UTC
sometimes, when I log in Whatsapp and the new messeges are loaded, there is displayed that I recieved i.e. two new messeges in one chat, and also the beginning of the messege is shown, but when I open the chat, there is no knew messege.
I had this problem by now only with whatsapp, but it also could be a problem in general, i don't know, i rarely use xmpp or other.

**Comment by TitanNano** [comment] 2015-05-19 20:14
hmm okay this is strange. does it happen a lot?

2015-05-19 22:06 GMT+02:00 tibtab notifications@github.com:

**Comment by tibtab** [comment] 2015-05-19 20:30
no it happens not often

**Comment by TitanNano** [comment] 2015-05-19 20:32
I see. I assume it is some kind of problem while saving the message. maybe
the app restarts right while writing to the indexedDB or something.

2015-05-19 22:30 GMT+02:00 tibtab notifications@github.com:

**Comment by ghost** [comment] 2015-05-20 16:35
could that issue be related to #708 or #532?

**Comment by TitanNano** [comment] 2015-05-20 16:48
not related to both of them but they are duplicates

**Comment by cmeerw** [comment] 2015-05-25 18:14
Unfortunately, commit 936d16131edcfc4c275a585ce6866bd9a6dfc9bb has completely broken XMPP - getting a TypeError in message.js, line 138 when receiving a message.

**Comment by TitanNano** [comment] 2015-05-25 19:24
oh oh oh yes I see the problem. I'll fix this as soon as possible.

**Comment by cmeerw** [comment] 2015-05-28 04:34
Is it just me or did this even break WhatsApp as I am seeing a TypeError in coseme.js, line 425

```
      this.ack(msgId, from);
```

(because "this" is not what the code expects it to be)

**Comment by TitanNano** [comment] 2015-06-04 07:02
I think this is finally fixed now.

**Comment by tibtab** [comment] 2015-06-13 10:26
I still have this problem

**Comment by TitanNano** [comment] 2015-06-13 10:28
can you tell when it occurs?

**Comment by tibtab** [comment] 2015-06-13 10:39
before updating I had it when a message was written to me while I wasn't available. Now loqui was running in background. I don't know if it's still a problem when im not online and receive the message afterwards.

**Comment by TitanNano** [comment] 2015-06-13 10:42
hmmm I really can't tell why this is happening. we wait until the message is saved before we send a acknowledgment to the server :-/ so even if the message wouldn't be saved for any reason, you should receive it again.

**Comment by tibtab** [comment] 2015-06-13 10:52
two messages were sent to me but I only received the second
![2015-06-13-12-19-18](https://cloud.githubusercontent.com/assets/11966750/8144068/02404244-11cb-11e5-9d1d-3d420d81bc1d.png)

**Comment by ghost** [comment] 2015-06-13 12:42
Same here "message7" was sent, too but not received.
![png image 320 x 510 pixels](https://cloud.githubusercontent.com/assets/4523264/8144331/b53ab5ce-11d9-11e5-91af-da19a740283c.png)
Clients: Firefox OS Simulator 1.4 (receiver) and Firefox OS Simulator 2.0 (sender) both with Loqui IM dev-branch

**Comment by ghost** [comment] 2015-06-13 12:54
Steps i could reproduce it several times with Firefox OS Simulator (1.4 as receiver and 2.0 as sender):

Receiver:
1. write a message to sender 
2. turn off internet connection (i used the wifi switch of my laptop)
3. quit Loqui IM

Sender:
1. write 3 messages to receiver

Receiver:
1. turn on internet connection
2. start Loqui IM

Why is there a difference between the message count and the display messages?

**Comment by TitanNano** [comment] 2015-06-13 18:33
can you try to reproduce this while your device is attached to the
debugging console? I'm not sure what's going on inside the Application.

2015-06-13 14:54 GMT+02:00 bobcanthelpyou notifications@github.com:

**Comment by ghost** [comment] 2015-06-14 01:26
Log 01: Receiver: http://pastebin.com/eubj87g4
1. start Loqui IM
2. receive msg01, msg02, msg03
3. write reply01 to sender
4. turn off internet connection
5. quit Loqui IM

Sender:
6. write msg04, msg05, msg06 to receiver

Log 02: Receiver: http://pastebin.com/H8hrjMZk
1. turn on internet connection
2. start Loqui IM
3. receive msg05, msg06

Result: 
![index](https://cloud.githubusercontent.com/assets/4523264/8146624/a3844a46-1244-11e5-9f6b-efb126b4914d.png)

**Comment by TitanNano** [comment] 2015-06-14 07:16
okay, you log clearly shows that we receive and acknowledge msg05. Means the message should be inside your device.... Can you check the chunks of your chat? I don't think the messages will be there but just to make sure.

**Comment by ghost** [comment] 2015-06-14 14:49
@TitanNano at which files i should have a look at?

**Comment by TitanNano** [comment] 2015-06-14 19:26
not a file. The messages chunks of your chat. I'm not sure if you know how
to do that.

2015-06-14 16:49 GMT+02:00 bobcanthelpyou notifications@github.com:

**Comment by ghost** [comment] 2015-06-14 19:33
@TitanNano Where are these chunks saved? Or how could i access these chunks?

**Comment by TitanNano** [comment] 2015-06-14 19:37
select your account, open the console:

``` JavaScript
Accounts.current.core.chats
```

there you have the chats and the chats hold an array `chunks` with the
block Ids of the chunks. you can load them with:

``` JavaScript
Store.recover(id, chunk => console.log(chunk));
```

**Comment by ghost** [comment] 2015-06-14 20:14
Ah okay 'msg04' is missing within the chunks

**Comment by TitanNano** [comment] 2015-06-14 20:16
okay. I think I need to have an other look into the saving and loading logic of the Stores.

**Comment by ghost** [comment] 2015-06-14 21:14
Maybe it is not a saving problem at all, maybe the unexpected disconnect of the internet connection is the problem, if i don't switch off the connection i can't reproduce the problem. If i quit Loqui IM while connected to the internet, someone is sending me message, starting Loqui IM again, everything is fine.

What does Loqui when the connection of Firefox OS get lost? (disconnect wifi / mobile data connection while Loqui is running or still connected but the connection is broken)

**Comment by TitanNano** [comment] 2015-06-15 08:12
Firefox OS will notify us about the disconnect and we will disconnect all accounts. As soon as we receive a online event we reconnect.
The problem is, the message arrives in our Application and does get saved. But what I think interferes here is the following scenario: 

contact reads our message we receive an ack for that -> loqui puts it in the queue

contact sent a message -> we receive it and request the last messages chunk -> we get copy1 of the chunk it contains [msg1, msg2, msg3]

the queue also requests a copy of the chunk to alter the excising message -> we get copy2 it contains [msg1, msg2, msg3]

We save our new message and write the chunk to the storage -> we save [msg1, msg2, msg3, msg4]

we save our altered message -> we save [msg1, msg2(changed), msg3]

I hope it's understand able, we lose msg4 because copy2 does not know of the changes which are made in copy1.

I'm thinking of always working on one single copy of a chunk, but I need to figure out when we can delete it from the memory. Otherwise we would run out of memory after some time.

**Comment by holztest08** [comment] 2015-08-24 13:06
I stlill have the problem of lost messages in 4.4a (but displayed in preview).

**Comment by TitanNano** [comment] 2015-08-26 02:08
I'm working on this, but i'm on vacation right now so have a little
more patience :) I hope to land a patch soon.

2015-08-24 13:06 GMT, holztest08 notifications@github.com:

> I stlill have the problem of lost messages in 4.4a (but displayed in
> preview).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/loqui/im/issues/719#issuecomment-134194754

## 

-- Jovan

**Comment by holztest08** [comment] 2015-09-29 17:27
In 4.6. the problem doesn't occure anymore. Sometimes I'm receiving messages double, but they don't get lost.

**Comment by TitanNano** [comment] 2015-09-29 17:32
great

**Closed as completed by TitanNano** 2015-09-29 17:32 UTC
