### ISSUE TITLE
Authentication failed message does not disappear

### ISSUE THREAD

**Issue by ghost** [loqui/im#523] opened 2014-09-13 08:47 UTC
At the moment Loqui IM is stuck in a problem, the "Authentication failed" message does not disappear, i could move it away/up but it always appears again, immediately.

It does not help to close/restart Loqui IM, or to restart Firefox OS, the Jabber account was working before and i could connect to it with my desktop jabber client.

![failed](https://cloud.githubusercontent.com/assets/4523264/4259988/c4c15e02-3b20-11e4-94dc-6004593aaa05.png)

The following message is repeated on the debugging console:

```
not well-formed index.html:1
"RECV" "userid@jabberdomain.tld" "<body xmlns='http://jabber.org/protocol/httpbind'><parsererror>XML Parsing Error: not well-formed
Location: app://{d0e3fb6f-8c37-479f-9e92-21ae54eae90a}/index.html
Line Number 1, Column 2:<sourcetext>&lt;/stream:stream&gt;
-^</sourcetext></parsererror></body>" tools.js:7
"Connection failed" tools.js:7
"Disconnected" tools.js:7
"Connecting" tools.js:7
"SENT" "userid@jabberdomain.tld" "<stream:stream to='jabberdomain.tld' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0'>" tools.js:7
not well-formed index.html:1
```

Loqui IM v0.3.3a

**Comment by ghost** [comment] 2014-09-13 09:01
I managed to remove the xmpp account (using the short time frame before the message appears again) but now i am unable to add it again 

```
"Connecting" tools.js:7
"SENT" undefined "<stream:stream to='jabberdomain.tld' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0'>" tools.js:7
not well-formed index.html:1
"RECV" undefined "<body xmlns='http://jabber.org/protocol/httpbind'><parsererror>XML Parsing Error: not well-formed
Location: app://{d0e3fb6f-8c37-479f-9e92-21ae54eae90a}/index.html
Line Number 1, Column 2:<sourcetext>&lt;/stream:stream&gt;
-^</sourcetext></parsererror></body>" tools.js:7
"Connection failed" tools.js:7
"Disconnected" tools.js:7
```

**Comment by aesedepece** [comment] 2014-09-13 10:18
I have experienced this when trying to access the same XMPP account from two different instances of Loqui IM. As the resource is always the same, they fight each other for connecting. We could add a random string at the end of the resource to avoid this.

**Comment by ghost** [comment] 2014-09-13 11:22
I am only using one instance of Loqui IM at one device. I added my XMPP account with a resource like this: userid@jabberdomain.tld/resource (my added resource is "ffos" and it is shown as ffos/Loqui at my desktop client). Maybe Loqui or a random string should not be added when the user set the resource manually. (Also the input field when adding a XMPP account should not marked red/invalid when adding a resource at the end of the user id)

**Comment by ghost** [comment] 2014-09-13 11:57
Is it maybe possible to prevent such loop situations and turn an account offline after several connection tries (may 10 times)

**Comment by aesedepece** [comment] 2014-09-13 16:08
Ok, this was caused by a misconfiguration in the BOSH gateway and is fixed now.
Sorry for the inconveniences :wink:

**Closed as completed by aesedepece** 2014-09-13 16:08 UTC
