### ISSUE TITLE
Problems with Conversation Color Code

### ISSUE THREAD

**Issue by tibtab** [loqui/im#823] opened 2015-09-16 18:53 UTC
Since the Update to 0.4.5 messages usually have a yellow background for about 30 seconds, when the receiver isn't active in this time, the messages are changing to red border with grey background. So most messages are looking like this, I had only which changed at some point to red background. It's a little bit confusing, because I'm never sure if the person I'm writing to is receiving my messages.

**Comment by cmeerw** [comment] 2015-09-16 19:17
So did the messages with grey background get delivered? Do you have any logs?

**Comment by TitanNano** [comment] 2015-09-16 20:00
are we talking about XMPP or WhatsApp? I just did a quick test and sending a message to my WhatsApp test group worked. the message was marked sent almost immediately.

**Comment by tibtab** [comment] 2015-09-16 20:24
I think they get delivered but I'm not sure if all of them get delivered.
while searching for a log I looked at the time and date of the messages and I'm not sure but i think that it first accured, not after the installation of 0.4.5 but after I ran this command:

```
adb shell
logcat -b main -v time | grep "/Loqui IM(" | gzip -c >/storage/sdcard/loqui.log.gz &
```

and now with loqui connected to the webide and usb connection (so loqui can't write to the log) everything seems to work again. Anyway I found some log of an message which is displayed with  red border and grey background for me:

```
09-15 16:34:49.621 I/Loqui IM(27976):  ~ BinaryWriter.prototype._write@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:4739:1 [BinaryWriter] 
09-15 16:34:49.621 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:56.241 I/Loqui IM(27976): Content JS LOG: SEND Oh ok scheiÃŸe [object Object] 
09-15 16:34:56.241 I/Loqui IM(27976):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
09-15 16:34:56.241 I/Loqui IM(27976): Content JS LOG: Write node called with  {"_tag":"message","children":[{"_tag":"body","children":[],"attributes":{},"_data":"Oh ok scheiÃƒÂŸe"}],"attributes":{"to":"Person1@s.whatsapp.net","type":"text","id":"1442327696-4"},"_data":null} ~ self._writeNode@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:7574:7 [ConnectionManager] 
09-15 16:34:56.241 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:56.241 I/Loqui IM(27976): Content JS LOG: <message to="Person1@s.whatsapp.net" type="text" id="1442327696-4">
09-15 16:34:56.241 I/Loqui IM(27976): <body>
09-15 16:34:56.241 I/Loqui IM(27976): Oh ok scheiÃƒÂŸe</body>
09-15 16:34:56.241 I/Loqui IM(27976): </message>
09-15 16:34:56.241 I/Loqui IM(27976):  ~ BinaryWriter.prototype._write@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:4739:1 [BinaryWriter] 
09-15 16:34:56.241 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:56.501 I/Loqui IM(27976): Content JS LOG: Received socket data: 58 bytes! ~ BinaryReader.prototype.onSocketData@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5177:5 [BinaryReader] 
09-15 16:34:56.501 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:56.501 I/Loqui IM(27976): Content JS LOG: <ack from="Person1@s.whatsapp.net" class="message" id="1442327696-4" t="1442327695">
09-15 16:34:56.501 I/Loqui IM(27976): </ack>
09-15 16:34:56.501 I/Loqui IM(27976):  ~ BinaryReader.prototype._readNextTree@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5272:7 [BinaryReader] 
09-15 16:34:56.501 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:56.501 I/Loqui IM(27976): Content JS LOG: FITS 
09-15 16:34:56.501 I/Loqui IM(27976):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
09-15 16:34:56.501 I/Loqui IM(27976): Content JS LOG: PUSHING 160 [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] 
09-15 16:34:56.501 I/Loqui IM(27976):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
09-15 16:34:56.501 I/Loqui IM(27976): Content JS LOG: SENT Person1@s.whatsapp.net 1442327696-4 
09-15 16:34:56.501 I/Loqui IM(27976):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
09-15 16:34:57.241 I/Loqui IM(27976): Content JS LOG: Received socket data: 56 bytes! ~ BinaryReader.prototype.onSocketData@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5177:5 [BinaryReader] 
09-15 16:34:57.241 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:57.241 I/Loqui IM(27976): Content JS LOG: <receipt from="Person1@s.whatsapp.net" id="1442327696-4" t="1442327696">
09-15 16:34:57.241 I/Loqui IM(27976): </receipt>
09-15 16:34:57.241 I/Loqui IM(27976):  ~ BinaryReader.prototype._readNextTree@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5272:7 [BinaryReader] 
09-15 16:34:57.241 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:57.251 I/Loqui IM(27976): Content JS LOG: DELIVERED Person1@s.whatsapp.net 1442327696-4  
09-15 16:34:57.251 I/Loqui IM(27976):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
09-15 16:34:57.251 I/Loqui IM(27976): Content JS LOG: Write node called with  {"_tag":"ack","children":[],"attributes":{"class":"receipt","id":"1442327696-4","to":"Person1@s.whatsapp.net"},"_data":null} ~ self._writeNode@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:7574:7 [ConnectionManager] 
09-15 16:34:57.251 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:34:57.251 I/Loqui IM(27976): Content JS LOG: <ack class="receipt" id="1442327696-4" to="Person1@s.whatsapp.net">
09-15 16:34:57.251 I/Loqui IM(27976): </ack>
09-15 16:34:57.251 I/Loqui IM(27976):  ~ BinaryWriter.prototype._write@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:4739:1 [BinaryWriter] 
09-15 16:34:57.251 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:35:00.141 I/Loqui IM(27976): Content JS LOG: Write node called with  {"_tag":"chatstate","children":[{"_tag":"paused","children":[],"attributes":{},"_data":null}],"attributes":{"to":"Person1@s.whatsapp.net"},"_data":null} ~ self._writeNode@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:7574:7 [ConnectionManager] 
09-15 16:35:00.141 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
```

**Comment by cmeerw** [comment] 2015-09-17 18:39
There should be a "Content JS LOG: MARKING AS SENT" entry in the log... Maybe there is something timing related that the "ack" gets processed too early and therefore doesn't trigger the "MARKING AS SENT" stuff...

**Comment by TitanNano** [comment] 2015-09-17 18:41
yes, I thought the same... @tibtab now it's working fine again?? after you stopped that logging command?

**Comment by tibtab** [comment] 2015-09-17 18:52
I dindn't stop it actively but it got stopped when I connected to the webide. Yes now it's working properly again.

**Comment by TitanNano** [comment] 2015-09-17 18:55
well I don't know why but I guess that was related to the background logging....

**Comment by cmeerw** [comment] 2015-09-17 19:21
This sounds very strange... @tibtab is this reproducible on your phone?

BTW, do you see any log entries with "MARKING AS" or "UNABLE TO FIND" in that log? It looks like the markMessage queue isn't being processed at all. Or do you see any Javascript exceptions/errors in the log?

**Comment by tibtab** [comment] 2015-09-17 21:05
I'll try to reproduce it.
There are no logs with "MARKING AS" but several with "UNABLE TO FIND".
Do you ment something like this: "Content JS ERROR" with Javascript error?

**Comment by TitanNano** [comment] 2015-09-17 21:07
unable to find is not good :/ can you provide them to us?

yea that's also an js error. we need to see them.

**Comment by tibtab** [comment] 2015-09-17 21:22
Error:

```
09-15 16:39:45.221 I/Loqui IM(27976): Content JS LOG: <stream:error>
09-15 16:39:45.221 I/Loqui IM(27976): <ack>
09-15 16:39:45.221 I/Loqui IM(27976): </ack>
09-15 16:39:45.221 I/Loqui IM(27976): </stream:error>
09-15 16:39:45.221 I/Loqui IM(27976):  ~ BinaryReader.prototype._readNextTree@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5272:7 [BinaryReader] 
09-15 16:39:45.221 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:39:45.221 I/Loqui IM(27976): Content JS LOG: null ~ BinaryReader.prototype._readNextTree@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:5272:7 [BinaryReader] 
09-15 16:39:45.221 I/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:39:46.801 E/Loqui IM(27976): Content JS ERROR: Error writing! {} ~ self._onErrorSendDisconnected@app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:7585:9 [ConnectionManager] 
09-15 16:39:46.801 E/Loqui IM(27976):     at putMessage (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3541:4)
09-15 16:39:46.801 E/Loqui IM(27976):     at Logger.prototype._message (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3483:4)
09-15 16:39:46.801 E/Loqui IM(27976):     at Logger.prototype.error (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:3471:4)
09-15 16:39:46.801 E/Loqui IM(27976):     at self._onErrorSendDisconnected (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:7585:8)
09-15 16:39:46.801 E/Loqui IM(27976):     at fire/< (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/mozillahispano/coseme.js:6028:8)
```

One of the "UNABLE TO FIND":

```
09-15 21:37:31.826 I/Loqui IM( 7932): Content JS LOG: UNABLE TO FIND MESSAGE! CARRY ON Person1@s.whatsapp.net 1442345850-0  
09-15 21:37:31.826 I/Loqui IM( 7932):     at Tools.log (app://{0ebd1812-eda1-4c22-81f0-36e495ee7d04}/scripts/loqui/tools.js:9:0)
```

The others of them are looking the same

**Comment by tibtab** [comment] 2015-09-18 16:27
And yes it is reproducible on my phone

**Comment by TitanNano** [comment] 2015-09-18 19:07
so if you turn on the logging again it won't work anymore?

**Comment by tibtab** [comment] 2015-09-18 19:21
yes

**Comment by TitanNano** [comment] 2015-10-22 11:41
I guess there is some platform issue while logging to a file at the same time here. I'll set it to wont fix.

**Closed as completed by TitanNano** 2015-10-22 11:41 UTC
Labels: wontfix
