### ISSUE TITLE
v.whatsapp.net respond Bad Token when I try to verify via sms the whatsapp account.

### ISSUE THREAD

**Issue by dogcalas** [loqui/im#702] opened 2015-05-01 21:46 UTC
I debug the code and I found that the coseme.js library from mozillahispano was an old version. Then I copy the last version and now always return bad token. With the old version the connection always return fail:oldversion.
![1](https://cloud.githubusercontent.com/assets/2521769/7437881/2fe657dc-f05c-11e4-97ae-c6fe197f6550.png)
![2](https://cloud.githubusercontent.com/assets/2521769/7437882/2ff20c80-f05c-11e4-853c-0017a3607b9c.png)

**Comment by ghost** [comment] 2015-05-01 22:19
Duplicate of #701

**Comment by TitanNano** [comment] 2015-05-02 13:54
right, I'll close this.

**Closed as completed by TitanNano** 2015-05-02 13:54 UTC

**Comment by kaank** [comment] 2015-07-14 08:50
Hi,

Please change this class in whatsappapi.dll 

  class WaToken {
        public static string GenerateToken(string number) {
            string s = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1430860548912" + number;
            byte[] bytes = Encoding.ASCII.GetBytes(s);
            byte[] value = MD5.Create().ComputeHash(bytes);
            return BitConverter.ToString(value).Replace("-", string.Empty).ToLower();
        }
        private static List<byte> GetFilledList(byte item, int length) {
            List<byte> list = new List<byte>();
            for (int i = 0; i < length; i++) {
                list.Add(item);
            }
            return list;
        }
    }

**Comment by tommed** [comment] 2017-11-24 10:13
^ doesn't work, still getting BAD TOKEN response :(
