### ISSUE TITLE
otr session error when resuming

### ISSUE THREAD

**Issue by pravi** [loqui/im#505] opened 2014-08-15 21:53 UTC
I get encrypted text when closing loqui and opening it again during an otr session. At the other end it is xabber which shows otr error.

**Comment by pravi** [comment] 2014-08-15 21:54
![blob](https://cloud.githubusercontent.com/assets/708222/3939409/ab50a948-24c6-11e4-8568-10d4f877bd4d.png)

loqui 0.3.2 on firefox os 1.3
zte open c

**Comment by pravi** [comment] 2014-08-15 21:57
Xabber had to be restarted to get it working again.

**Comment by ghost** [comment] 2014-09-06 08:53
Maybe related to #443

**Comment by pravi** [comment] 2014-09-06 09:13
@bobcanthelpyou yes, I also think it is the same problem. I have xabber on the other end but I can confirm the behaviour mentioned in #443

**Comment by ghost** [comment] 2014-09-11 08:46
@pravi could you reproduce this problem with Loqui IM 0.3.3a?

**Comment by pravi** [comment] 2014-09-11 08:54
@bobcanthelpyou , I will try to reproduce and update here.

**Comment by pravi** [comment] 2014-09-23 09:42
I got the same problem today on 0.3.3. I think loqui should cache otr session on file unless it is manually closed or when resuming it should send a reset request (close otr + open otr again). This is really irritating and makes loqui unusable with otr.

**Comment by bdcomp** [comment] 2014-09-29 05:19
@aesedepece Is this fixed by your https://github.com/loqui/im/commit/e89c575ead408bef6e4544a97e9e6c192e6f9efb

**Comment by aesedepece** [comment] 2014-09-29 07:51
@bdcomp Yes, I'm not able to reproduce this issue any more :smiley_cat:

**Closed as completed by aesedepece** 2014-09-29 07:51 UTC
Labels: bug

**Comment by pravi** [comment] 2014-10-20 17:39
When ChatSecure is at the other end, often I get "I could not decrypt the message you send". It happens when I resume the conversation after a long time. It could be a bug at ChatSecure end. When the chat is closed, it should signal OTR session is ended. Can there be an option to check if OTR session is active after a timeout and restart the OTR session?
