### ISSUE TITLE
Improvements for Loqui

### ISSUE THREAD

**Issue by gabriel-lucas** [loqui/im#154] opened 2013-12-17 22:49 UTC
Hi, 

I have some suggestions / bugs I found that could improve Loqui.
- when showing contact list, the profile photograph doesn´t load until you start a conversation with that contact. It would be good to load them all together at the beginning.
- Once installed Loqui, if you update a contact in firefox contact webapp, list of contact in Loqui doesn´t updates.
## Bugs
- When adding whatsapp account, the sms that arrives uses a '-' character to separe two groups of three digits each as a validation code. But when using it to validate it just gets it right when you take the '-' character out.
- Once you have chat with more than one contact, the conversation appears repeated many times and doesn´t show the other ones.

Hope this helps :)

**Comment by aesedepece** [comment] 2013-12-18 02:14
- Downloading hundred of contact pics is not a good idea if you are connected through data plan...
- There's a refresh button on the right side of the search bar in the contacts list. Tap it and your contacts will be synced.
- I'll check it, but I think the '-' character was automatically taken out.
- Duplicate of #149, already fixed ;)

Thanks for all!

**Comment by Gioyik** [comment] 2013-12-31 07:39
This is fixed in v0.2.4

**Closed as completed by Gioyik** 2013-12-31 07:39 UTC
