### ISSUE TITLE
No contact update with git version

### ISSUE THREAD

**Issue by deimidis** [loqui/im#174] opened 2013-12-27 21:16 UTC
Hi everyone, I tried to change some contacts to add the bad Argentina's number and then try to update Loqui contact list, but I couldn't. I made click to the arrow near the top screen on Contacts list, but nothing happens

**Comment by deimidis** [comment] 2013-12-27 21:44
[JavaScript Error: "Error: Permission denied to access property 'tagName'" {file: "app://8756f3b1-886e-4e48-99d4-31b6ad390a9a/scripts/tapquo/quo.js" line: 1028}]

Este es el error que aparece en la consola cuando hago clic en la flecha

**Comment by Gioyik** [comment] 2014-01-04 06:56
Yes, the problem is that quo.js doesn't recognize getElementsByTagName. Now it's fixed with the commit added to the Pull Request for the v0.2.5 (#178). If the problem continues, reopen this issue a paste again a logcat with the error.

Thanks for report it.

**Closed as completed by Gioyik** 2014-01-04 06:56 UTC
