### ISSUE TITLE
show owner of a group on "Group Info"

### ISSUE THREAD

**Issue by ibinshoid** [loqui/im#899] opened 2015-12-03 18:22 UTC
when i open a whatsapp group and click on the image on the right top corner i get to the group info. there i can see the count of participants and the names of all participants, but not who of then created the group and invited me to this group. i think this would be a usefull information to schow.

**Comment by TitanNano** [comment] 2016-01-07 15:40
duplicate of #901

**Closed as completed by TitanNano** 2016-01-07 15:40 UTC
Labels: duplicate
