### ISSUE TITLE
XMPP: invitation to a conference room

### ISSUE THREAD

**Issue by ghost** [loqui/im#520] opened 2014-09-11 09:37 UTC
When i get a invitation for a conference it looks like the following:

A new chat with the following message is opened:

user@jabberdomain.tld invites you to the room example@conference.jabberdomain.tld (invitation message)

Within that chat i only could talk to myself. And i need to access the conference room manually.

I would expect a button to enter the conference room easily. Maybe a question "Do you want to access that room?" or something like that

**Comment by ghost** [comment] 2014-09-16 15:56
Would it be useful to add a question function to chungo.js "Lungo.Notification.question" for this? Or is there an other place to handle questions and user interactions? Maybe i could write some code for this, but at the moment i am not sure where the code should be added.

**Comment by aesedepece** [comment] 2014-09-28 10:59
Duplicate of #353. Thanks!

**Closed as completed by aesedepece** 2014-09-28 10:59 UTC
Labels: duplicate, JS, UX, P2, suggestions
