### ISSUE TITLE
[Whatsapp] Same message multiple times in group

### ISSUE THREAD

**Issue by decode-dev** [loqui/im#985] opened 2016-03-24 05:41 UTC
After the login problem is solved
Same message / media is repeated multiple times (6-10 times) in a group.

**Comment by cmeerw** [comment] 2016-03-24 08:59
Waiting for marketplace to approve version 0.5.1

**Comment by Nordfriese57** [comment] 2016-03-24 09:04
I have the same behaviour in a new group. The other groups are ok. The messages are repeated every 2 to 5 Minutes.  
Deleting the conversation does not work.

**Comment by Nordfriese57** [comment] 2016-03-24 09:06
I will wait. Thank you. If the problem is fixed I'd like to donate. How can i do that?

**Comment by decode-dev** [comment] 2016-03-24 18:40
I have built the latest version. [0.5.1a]
But the problem still persists.

**Comment by Honk2** [comment] 2016-03-24 20:30
Is there a difference between the Marketplace version and 0.51a?

**Comment by Honk2** [comment] 2016-03-24 20:32
I also installed 0.51a and text messaged appear  once, media multiple times.

**Comment by tibtab** [comment] 2016-03-24 21:56
By now I don't receive any messages and acks any more. It was working until today round about 14:00 GMT +1

**Comment by botswan** [comment] 2016-03-25 22:29
The same is happenin now to me but the worst thing for me i cant be able to recieve other texts

**Comment by botswan** [comment] 2016-03-26 08:53
How can i have the new versions 0.51a my app have the same problem. Um unable to see updates

**Comment by Honk2** [comment] 2016-03-26 09:49
I am not sure if this infohelps:
i am using 0.5.1a, answering to an image prevents multiple receives of that image.
Although i do not get double blue ticks,  my messages are delivered immediately to groups.

**Comment by ElPopi** [comment] 2016-03-26 15:58
Same issue, repeated messasges from groups.
No double green tick nor blue tick from sent and received messages.
Not receiving other messages

**Comment by janu2015** [comment] 2016-03-27 23:10
This is an (anonymized) group chat log. Same image ("file.jpg") is received 8 times. 

[2016-03-26_0.log.txt](https://github.com/loqui/im/files/191183/2016-03-26_0.log.txt)

**Comment by cmeerw** [comment] 2016-03-27 23:31
@janu2015 which version is that log for? That should be fixed with current git sources (past 0.5.1)

**Comment by decode-dev** [comment] 2016-03-28 18:19
@cmeerw 
Can you send me the Update on the Marketplace Status on loqui.
Will ask my Mozilla team to look into it
ASAP.

**Comment by cmeerw** [comment] 2016-03-28 18:21
0.5.1 has been in the review queue for one week - I am just about to upload 0.5.2 in the next few minutes...

**Comment by cmeerw** [comment] 2016-03-28 18:43
I have just uploaded 0.5.2 to the marketplace...

**Comment by janu2015** [comment] 2016-03-28 23:27
@cmeerw The log is created by the version I built at March 24th around noon from git sources (plus my logging workaround) --> v0.5.1.
#986  "fixed receipts for group media messages" hasn't been included then.

I just built and installed v0.5.2 and I'm curious about it :-)

Nice emojis and better handling, by the way. Thank you and @Honk2 :-)

**Comment by sagardahale** [comment] 2016-03-29 06:58
@cmeerw i dont found 0.5.2 version on marketplace

**Comment by sagardahale** [comment] 2016-03-29 14:12
Can anyone help me? I cant recieve msgs from whatsapl groups

**Comment by cmeerw** [comment] 2016-03-29 20:44
@sagardahale 0.5.2 is in the marketplace review queue... BTW, do you have any logs?

**Comment by sagardahale** [comment] 2016-03-30 00:36
@cmeerw can i install it by downloading zip file from releases?

**Comment by Honk2** [comment] 2016-03-30 08:29
Yes. Look at the wiki how to build and install loqui.
Keep in mind, that you will not get automatic updates with your own build.
If you want to keep your history, you also need to do a backup before updating.

**Comment by cmeerw** [comment] 2016-03-30 08:33
If you download the 0.5.2 release zip from github you don't need to
build, just unzip and install.

**Comment by sagardahale** [comment] 2016-03-30 11:04
I unzipped it.how to install?

**Comment by cmeerw** [comment] 2016-03-30 11:16
You can install via the Firefox WebIDE.

But 0.5.2 has just been approved on the marketplace, so you should be
able to update from the marketplace.

**Comment by sagardahale** [comment] 2016-03-30 12:02
@cmeerw i updated it..BTW you really did a great job..thank you

**Closed as completed** 2016-03-30 17:12 UTC
