### ISSUE TITLE
[xmpp] autoreconnect is not working

### ISSUE THREAD

**Issue by pravi** [loqui/im#674] opened 2015-03-31 18:06 UTC
I have to manually disconnect and reconnect all the time. I think there should be a time based reconnect for really bad connections. Every 5 minutes its should try, if 3 tries fail, it should try every half an hour and if 3 such tries fail, then after every two hours. For me once it is offline, it never econnects by itself.

**Comment by TitanNano** [comment] 2015-03-31 19:23
duplicate of #516

**Closed as completed by TitanNano** 2015-03-31 19:23 UTC
