### ISSUE TITLE
Set a timeout when setting up an account

### ISSUE THREAD

**Issue by willyaranda** [loqui/im#129] opened 2013-12-02 14:22 UTC
If I try to set up an account (mozilla-hispano.org with hangouts), it seems that it fails, but it is stuck on "Connecting" and the only way to get out of that screen is just closing and opening the app.

It will be fantastic if you put a 10-15 seconds timeout so users will not wait forever.

**Comment by Gioyik** [comment] 2013-12-04 07:33
Hi @willyaranda, i pushed a commit with a fix for this bug, so please, test and tell me if it's Ok! i set as timeout 15 seconds. Let me know if all is great to close this issue. :)

**Comment by Gioyik** [comment] 2013-12-04 16:49
Ok, there was a problem with the commit. When you log in successfully into an account and you wait 15 seconds it shows you the timeout message, so, this is a wrong behavior. I am going to fix it.

**Comment by Gioyik** [comment] 2013-12-04 16:53
Seems to work great. Please test it and tell me if everything is OK! to close the issue.

**Comment by willyaranda** [comment] 2013-12-04 16:55
I don't think this is the correct behaviour. If the auth fails, just show the error without the timeout (you have a problem, and you wait 15 seconds to show the message? :)). This is expecting loqui caughts the authfail event, BTW.

**Comment by Gioyik** [comment] 2013-12-04 17:08
I removed the timeout, seems reasonable that you pointed. Tell if it's ok to change the text in the notification.

**Comment by willyaranda** [comment] 2013-12-04 17:18
No debería usar `Lungo.Notification.error`?

**Comment by aesedepece** [comment] 2013-12-04 17:19
There's already a message shown when auth fails. But it's only fired when the server actively refuses the connection: if the problem is due to a network error nothing happens.

And YES, it should be `.error` instead of `.success`. Lol.

**Comment by Gioyik** [comment] 2013-12-04 17:22
Jajajajjaa sorry, now is fixed :P

**Comment by Gioyik** [comment] 2013-12-04 17:29
I added some code, see bc9f7bb6970b74763a66492056f228695bf87294 to notify when you fill data for an account like this:

username: ohgoisdhfis
password: hosjfoisfs

Let me know if everything is ok, to change the text in the notifications and stop making infinite commits with not pull requests :P

**Comment by Gioyik** [comment] 2013-12-04 18:04
Seems that everything is working well. If the problem continues reopen it and i will make the corrections in a Pull Request for review.

**Closed as completed by Gioyik** 2013-12-04 18:04 UTC
Labels: enhancement, JS, proposal, P2
