### ISSUE TITLE
Hangout for non-gmail address

### ISSUE THREAD

**Issue by LeTanque** [loqui/im#639] opened 2015-02-08 03:34 UTC
I have successfully enabled hangouts for my gmail address but cannot authenticate my business domain's address. 

My hangouts account works with Google Chrome's hangouts extension and through gmail, of course. 

I do not have 2fa enabled with the business domain so I should be able to simply use my password.
EDIT I do have 2fa enabled. Created an application password and that, too, didn't work.

CPU~Dual core Intel Core i7-2640M (-HT-MCP-) clocked at Min:841.203Mhz Max:1091.343Mhz Kernel~3.16.0-30-generic x86_64 Up~2:42 
Mem~1982.5/7867.4MB 
HDD~271.6GB(33.3% used) 
Procs~235 Client~Shell
Mozilla Firefox 35.0.1

![2015-02-07 19 22 47](https://cloud.githubusercontent.com/assets/7180772/6095071/3b9c7b5e-aeff-11e4-9d2d-5b74c1c6f36f.png)

**Comment by LeTanque** [comment] 2015-02-08 03:39
Added firefox version info

**Comment by aesedepece** [comment] 2015-02-08 14:00
This is a duplicate of #79. In that issue's discussion you can find tips to get it working, though it will be really fixed when #122 eventually lands.

**Closed as completed by aesedepece** 2015-02-08 14:00 UTC
Labels: duplicate
