### ISSUE TITLE
[WhatsApp] [Ubuntu] decrypt error

### ISSUE THREAD

**Issue by hstarmans** [loqui/im#1187] opened 2017-02-11 12:41 UTC
Dear all,

I get a decrypt error when I receive Whatsapp Messages with my Ubuntu Phone using OTA-13 with Loqui Beta v0.5.11(all click) or _captions.click, see [releases](https://github.com/loqui/im/releases).
Loqui Beta v0.5.10 does not work at all. With 0.5.11, I can sent messages which other users can read.
I can, however, not read messages. Restarting the group or rejoining does not solve the issue.
If I start the application I also receive {{ContactsGetError}}. I do see all my conversations.
Any suggestions!? Can it work?

**Comment by nfsprodriver** [comment] 2017-02-11 14:32
Closing this this issue because it's a duplicate of #1157 Wait a few hour, days, then messaging may basically work.

**Closed as completed by nfsprodriver** 2017-02-11 14:32 UTC

**Comment by hstarmans** [comment] 2017-02-25 11:19
I can confirm that the messaging started to work after 2 weeks. I upgraded to Loqui IM 0.5.11_1 and used OTA 15.
