### ISSUE TITLE
Keyboard is hidden when you send a message

### ISSUE THREAD

**Issue by nukeador** [loqui/im#94] opened 2013-11-28 23:23 UTC
It's very inconvenient that the keyboard is automatically hidden when you send a message, making you click again and again on the text area to send new messages.

**Comment by aesedepece** [comment] 2013-11-28 23:44
Duplicate of #85 

Tip: you can send messages without hidding the keyboard by typing the return key ;)

**Closed as completed by aesedepece** 2013-11-28 23:44 UTC
Labels: duplicate
