### ISSUE TITLE
Whatsapp can't receive messages

### ISSUE THREAD

**Issue by holztest08** [loqui/im#879] opened 2015-11-07 22:35 UTC
In 4.9b I can't receive messages from single buddies (only images work). Sending doesn't make any problems.

**Comment by TitanNano** [comment] 2015-11-08 06:05
we need you to do the following thing. 
Go to your app settings. Enable Developer mode, select the Dev tab in the settings and enable "Write Log Files". 
Then try to reproduce your problem. Ask some one to send you a few messages.
After you did that turn of the Log File setting.
You can find the log file on your sd card in /loqui/logs/ send us the content of the file or files on here and we will check it.

**Comment by cmeerw** [comment] 2015-11-08 10:53
likely the same encrypted message issue as #770

**Comment by TitanNano** [comment] 2015-11-08 10:53
yes i think so too.

**Comment by holztest08** [comment] 2015-11-10 21:39
My whatsapp account is locked for 2772 minutes... xD
so I couldn't write any log files. But before I had the problem I was logged in with an official client (latest android version). I think it's the same problem as [#770](https://github.com/loqui/im/issues/770)

**Comment by cmeerw** [comment] 2015-11-10 21:53
closing this one as a duplicate of #770 then...

**Closed as completed by cmeerw** 2015-11-10 21:53 UTC

**Comment by cmeerw** [comment] 2015-11-13 16:45
@holztest08 is your account active again? Any chance in testing if the recent changes fix this issue?

**Comment by holztest08** [comment] 2015-11-17 08:34
Yes, but I get this error executing grunt:

Running "clean:build" (clean) task

> > 3182 paths cleaned.

Running "execute:renderersCompiler" (execute) task
-> executing /home/holztest/loqui/im/renderersCompiler.js
/home/holztest/loqui/im/node_modules/jsdom/lib/jsdom.js:3
`jsdom 4.x onward only works on io.js or Node.js 4 or newer: https://github.co
^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/holztest/loqui/im/renderersCompiler.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
Warning: -> error 1 /home/holztest/loqui/im/renderersCompiler.js (111ms) Use --force to continue.

Aborted due to warnings.

**Comment by cmeerw** [comment] 2015-11-17 08:57
Try updating nodejs, see https://github.com/nodesource/distributions
