### ISSUE TITLE
[WhatsApp] latest message preview in chat list is different to the actual latest message

### ISSUE THREAD

**Issue by ghost** [loqui/im#708] opened 2015-05-06 13:44 UTC
Sometimes messages are shown in the last chats list as a preview of the last / newest message but when i access the chat the last message is not displayed / not the same.

I am not sure if i can't access the newest message at all and they disappears (i only see the preview snippet in the last chats list), especially when i write / answer to the contact before the message is displayed in the chat window.

Firefox OS v2.0 / Loqui IM v0.4.2b

**Comment by gargsms** [comment] 2015-05-06 14:14
I can confirm that.

**Comment by TitanNano** [comment] 2015-05-06 14:50
yes I know and I know why. thanks for reporting. don't we have a issue for this already? I'll fix it soon ;-)

**Comment by TitanNano** [comment] 2015-05-06 15:23
duplicate of #532

**Closed as completed by TitanNano** 2015-05-06 15:23 UTC
Labels: duplicate

**Comment by ghost** [comment] 2015-05-20 16:33
I am not sure if it is the same like #532 there are the messages out of order but within the chat history

My issue is that some messages don't appear within the chat history, i only see them as the last message in the list of the chats as a teaser / preview, but these messages are lost somehow

**Comment by TitanNano** [comment] 2015-05-20 16:46
no they are different.
