### ISSUE TITLE
[Whatsapp] Doesn't update current chats

### ISSUE THREAD

**Issue by juaneladio** [loqui/im#116] opened 2013-11-30 23:55 UTC
I noticed that I don't receive conversations while I'm connected. I have to close the app and reopen it in order to get new messages.

**Comment by aesedepece** [comment] 2013-12-01 02:47
This bug has been reported to the developers in charge of the whatsapp connection library and will likely be fixed by monday or tuesday. Thanks.

**Comment by aesedepece** [comment] 2013-12-01 02:48
This is duplicate of #112

**Comment by Gioyik** [comment] 2013-12-01 02:49
Closed. 

Reason: Duplicated

**Closed as completed by Gioyik** 2013-12-01 02:49 UTC
Labels: bug, duplicate, JS
