### ISSUE TITLE
[XMPP] Feature request: Connecting directly to a user chosen jabber server

### ISSUE THREAD

**Issue by ghost** [loqui/im#405] opened 2014-05-25 19:58 UTC
It would be nice to be able to connect directly to a server the user choses. Like in Adium, Pidgin and all other clients.

This could be a feature for the future. I guess there are other priorities for xmpp on loqui right now.

**Comment by aesedepece** [comment] 2014-05-25 19:59
Duplicate of #365

**Closed as completed by aesedepece** 2014-05-25 19:59 UTC
Labels: duplicate

**Comment by ghost** [comment] 2014-05-25 20:08
oh i did not realize that. My bad ;-)
