### ISSUE TITLE
Facebook chat not working

### ISSUE THREAD

**Issue by jeancayron** [loqui/im#932] opened 2016-01-27 19:44 UTC
Since december 2015 it is not possible any more to connect to Whatsapp.
It constantly says "Authorisation failed".
The same problem occurs on my Linux system with telepathy. Facebook might have changed something to their API?

**Comment by cmeerw** [comment] 2016-01-27 20:02
do you mean facebook or WhatsApp, in case of facebook it's a duplicate of issue #700

**Closed as completed by cmeerw** 2016-01-27 20:02 UTC

**Comment by jeancayron** [comment] 2016-01-27 20:18
I meant Facebook. Sad thatit can't be solved.
Thanks.
