### ISSUE TITLE
Can't create new chat

### ISSUE THREAD

**Issue by MarkTr** [loqui/im#714] opened 2015-05-12 19:32 UTC
Installed loqui on may 11. Can't write to contact. I can click on the pen symbol and chose a contact but no window for writing opens. Device is Mozilla Flame

**Comment by TitanNano** [comment] 2015-05-12 19:38
Which provider are you using? what happens? just nothing? do you get directed back to the main view?

**Comment by MarkTr** [comment] 2015-05-12 20:06
I tried with whatsapp and Google hangouts.I can reply to existing chats. Yes it gets me to the providers main view

**Comment by TitanNano** [comment] 2015-05-12 20:07
okay this is a duplicate of #707 you can find a workaround over there.

**Closed as completed by TitanNano** 2015-05-12 20:07 UTC
Labels: duplicate
