### ISSUE TITLE
multi-account

### ISSUE THREAD

**Issue by mautematico** [loqui/im#55] opened 2013-10-11 03:28 UTC
I love loqui. And I wish it to be multiaccount.

**Comment by aesedepece** [comment] 2013-10-11 09:51
Duplicate of https://github.com/waalt/loqui/issues/29

Anyway...  Good news! Loqui IM v0.1 will be released next week and it's multi-account.

**Comment by mautematico** [comment] 2013-10-13 01:40
Great! :D

**Comment by aesedepece** [comment] 2013-10-15 19:15
Closed by 7129fe9f3cc45f227e8303885cdcaae3b6400287.

**Closed as completed by aesedepece** 2013-10-15 19:15 UTC
Labels: duplicate
