### ISSUE TITLE
Allow URL sharing

### ISSUE THREAD

**Issue by airon90** [loqui/im#508] opened 2014-08-20 17:40 UTC
Is it possible to add URL sharing?

https://github.com/loqui/im/blob/dev/manifest.webapp#L67

Adding URL sharing it will be possible to send url to someone or to create a message with a url already inserted

Here is why I made this request: http://tracker.user1.be/SimpleRSS/64/#127

**Comment by aesedepece** [comment] 2014-08-21 19:03
:+1:

**Comment by ghost** [comment] 2014-09-30 09:39
Is this a duplicate of #534 ?

**Closed as completed** 2014-11-24 13:38 UTC
Labels: duplicate, enhancement, JS
