### ISSUE TITLE
unable to log on to Hangouts (Google Apps)

### ISSUE THREAD

**Issue by ghw** [loqui/im#377] opened 2014-05-02 03:07 UTC
The use of Google Apps(google.com/apps), unable to log on to Hangouts (show the password is wrong, but I can ensure that the password is not wrong, because this password can login XMPP version)

**Comment by aesedepece** [comment] 2014-05-02 10:16
Duplicate of #79. Let's track it there.

**Closed as completed by aesedepece** 2014-05-02 10:16 UTC
