### ISSUE TITLE
[WhatsApp] unable to manually add contacts

### ISSUE THREAD

**Issue by pravi** [loqui/im#185] opened 2014-01-06 03:18 UTC
Loqui 0.2.4

add button doesn't work. There should be an option to import contact from addressbook. Also when unknown person sends a message, I cannot create contact.

**Comment by iacchi** [comment] 2014-01-20 08:02
I can confirm this, same version.

**Comment by aesedepece** [comment] 2014-01-20 11:10
By now, you have to add the contact in your phone address book and then press the "sync" button in the upper right side of the contacts list in Loqui. I know it's not convenient, we'll improve it asap.

**Comment by iacchi** [comment] 2014-01-20 11:46
That would have been easy, and I've tried it already. It still doesn't work.

**Comment by iacchi** [comment] 2014-01-28 08:41
Sync with address book is not working even in v.0.2.5

**Comment by TitanNano** [comment] 2014-11-19 16:20
duplicate of #255

**Closed as completed** 2015-01-21 16:11 UTC
Labels: enhancement, UX, P2
