### ISSUE TITLE
Update to 0.3.2

### ISSUE THREAD

**Issue by ghost** [loqui/im#481] opened 2014-07-29 20:35 UTC

**Comment by bdcomp** [comment] 2014-07-30 04:49
I think that as long there are several bugs fixed per week, we should release on a timely basis.
About every 6 weeks, like Firefox, sounds great.

**Comment by Gioyik** [comment] 2014-07-30 19:22
Hi,

LoquiIM is developed by many people that contribute in his own way. We start to organize LoquiIM development, time ago because It was crazy the release number management. Two fixes, an incremental release, then, one fix, an incremental release and that happens for a long time. I am concerned about organization is important.

I know that LoquiIM has some problems related to XMPP and will be incredible solve all of them. Off course, a release time schedule should be great to have, _but_ It will be complicated because that means we **must** finish the bugs yes or yes, and dedicate full time to resolve them. The point is that I know most of the contributors here help a lot to LoquiIM and improve it _when there's free time to dedicate it_ including @aesedepece and I include myself (yes we have social life :P).

So, I think that have a release time schedule will push us to have things done in a certain time and in some cases there's not a lot of free time to dedicate to solve all the issues or could be present some situations that don't let us accomplish with everything on time. It's normal and happens.

Solutions I can propose:
- +1 to P1 issues
- Use milestones to put there the issues we like to have solved for next release
- Have fun contributing

By the way, keep the good work to all the people is helping a lot on issues and moving LoquiIM. You are great.

P.S The comment is just an opinion, not a decision or something related. Just words to take in count to decide the better way to organize.

**Comment by Gioyik** [comment] 2014-07-30 19:37
I don't think this should be closed, there's some people that maybe could say something related to this or express their opinion about it. Maybe with this issue we can find the better way for a fast and a good work flow to important issues :)

**Comment by aesedepece** [comment] 2014-07-31 13:15
I agree we should release 0.3.2 as soon as possible as 0.3.1 renders XMPP unusable. Any objection? @aarizkuren @bdcomp 

We could also release a weekly-updated "Loqui DEV" app in the Marketplace so that most avid users can test new features more often and we can get early feedback for the sake of better stable releases.

Those users and developers who want to have more influence on future decisions can also subscribe to the loqui.core mailing list at:
http://lists.waalt.com/cgi-bin/mailman/listinfo/loqui.core

**Comment by bdcomp** [comment] 2014-07-31 14:11
No objections :)

**Comment by Gioyik** [comment] 2014-08-03 04:03
Hola,

Pensando en lo que se habia comentado aquí hace unos días sobre el desarrollo de LoquiIM y demás, se me ha ocurrido ingeniarme alguna forma de tener un medio para crear los paquetes en donde LoquiIM va a estar disponible. Por si no se sabia, ando trabajando en el port de LoquiIM a Ubuntu Touch, y en el cliente desktop (linux, mac y windows) el cual está hecho con node-webkit. Como LoquiIM es una aplicacion hecha por completo en HTML5, CSS y Javascript, me parece un poco tonto tener que separar por branches para cada plataforma y que si se hace un cambio en LoquiIM, luego se tenga que pasar esos cambios tambien a las otras branchs de las otras plataformas lo cual duplica trabajos y es mas dificil de mantener. 

He creado un pull request #484 con los cambios y como quedaria la estructura planteada. Realmente no ha cambiado nada en cuanto a LoquiIM, solo un poco la forma de hacer las cosas. Se usa nodejs y grunt, lo cual facilita mucho todo el proceso y lo que me parece muy bueno para implementar, es que teniendo ya una estructura con nodejs y grunt, podemos integrar Travis.ci con este repo en Github y crear tests. Así cuando se pasen commits, incluso en los mismos Pull request, Travis.ci se encargaría de hacer los test y decirnos si se ha roto algo o ha fallado algo, lo cual seria muy bueno porque nos ayudaria a identificar cosas que se han dañado y no que la gente las reporte despues y pase por las molestias.

El pull request no es necesario hacerle merge pronto, de hecho espero opiniones para ver que les parece la propuesta y de ser asi hacer los cambios que les parezca convenientes.

Recalco que con esos cambios y en esta branch se estaria generando los paquetes para FirefoxOS, Ubuntu Touch y los clientes desktop para todas las plataformas, lo cual me parece guay (lo aprendí de Adán) ya que hacemos los cambios a Loqui en un mismo lugar, y se aplica en todas las plataformas y luego no se vuelve una locura.

Ping!

@aesedepece como lo ves?

**Comment by bdcomp** [comment] 2014-08-03 05:19
@Gioyik I will appreciate English...

**Comment by louisdem** [comment] 2014-08-03 09:04
[Translated text]
<quote>
"Hi,
Thinking about what has been commented here for some days about the development [process] of LoquiIM and others, it occured to me to find a way of obtaining a medium for the creation of packages where LoquiIM would be available. Even though it wasn't yet known, I'm currently working on LoquiIM's port to Ubuntu Touch, and on the desktop version (linux, mac and windows), done with node-webkit. As LoquiIM is an application written fully in HTML5, CSS and Javascript, it seems a little foolish to me to separate in branches for each [supported] platform, when, for a example, a change is made in LoquiIM, soon this change [or changes] have to be done in all the other branches of supported platforms, which duplicates work and is harder to maintain.

I've created a pull request #484 with the changes showing how the new structure could be. I haven't really changed anything in regards to LoquiIM, only a little bit in the way of doing things. Nodejs and grunt are used, which eases much of the process and it looks good for me to implement it [in this way], it is that already having a structure with nodejs and grunt, we can integrate Travis.ci with this repo in Github and create tests. This way, when commits are made, including Pull Requests, Travis.ci would itself do the job of doing the tests and tell us if something was broken [with those commits/Pull Requests] or if there's a mistake somewhere, which would be very good because it would help us identify broken things, and not after the users report them and we get the blame.

[Regarding] The Pull Request [that I've made], it's not necessary to merge it immediately, from this I expect opinions to see what you think of this proposal and then make the changes that seem convenient for you.

I stress that with these changes and on this branch we would be generating packages for FirefoxOS, Ubuntu Touch and the desktop clients for all platforms, which seems good ['guay'] to me, since we would make changes to Loqui in one place, and those changes apply to all platforms, then it does not become [a] crazy [process].

Ping!

@aesedepece how do you see it?"

</quote>

**Comment by aesedepece** [comment] 2014-08-03 10:47
@Gioyik I need to test it, but at a first glance it sounds amazing.

Integrating Travis.ci or any other automated testing tool seems pretty appropriate and necessary at this time as it could spare us many regressions caused by new PRs.

Regarding v0.3.2, I'm synchronizing the locales in the repository with the ones in the translating platform (http://translate.loqui.im). Let's update the manifest and push the update at last.

PR #484 should be merged right after the `x-facebook-platform` branch is merged into `dev`. (This will enable logging into Facebook by using a regular FB Login button and no username/password)

**Comment by aarizkuren** [comment] 2014-08-04 19:59
Hi, and sorry for my english.

+1 to integrate automated testing tools, i think its necessary too, to avoid stupid bugs. But i think we have to recode a lot of loquis code to easy test it, im not testing expert, but i think the code is not optimized to it.

I like too the early-release option.

agur

**Comment by aarizkuren** [comment] 2014-09-02 11:12
We are going to do something with this?

**Comment by aesedepece** [comment] 2014-09-02 17:48
I haven't been able to make much progress with the `x-facebook-platform` branch, so I'd agree to release 0.3.2 asap and leave FB OAuth and #484 for 0.3.3 as the XMPP fixes are urgent.
Any :+1:?

**Comment by bdcomp** [comment] 2014-09-02 17:56
I think #513 is pretty urgent and it should be fixed before any release.

**Comment by aarizkuren** [comment] 2014-09-02 17:56
:+1:

**Comment by aesedepece** [comment] 2014-09-02 18:48
btw I meant let's update to v0.3.3 as v0.3.2 has been in the marketplace for weeks :laughing:

**Closed as completed** 2015-02-08 13:54 UTC
Labels: team, discussion
