### ISSUE TITLE
[WhatsApp] Some emoji are rendered badly

### ISSUE THREAD

**Issue by gargsms** [loqui/im#562] opened 2014-11-02 20:17 UTC
Few that I have found to be rendering improperly: 
![1f601](https://cloud.githubusercontent.com/assets/5238955/4876641/0a3271dc-62cd-11e4-99ab-65ad5224a028.png)
![1f52b](https://cloud.githubusercontent.com/assets/5238955/4876642/1813d228-62cd-11e4-8cd5-0b2f61240d49.png)

Here is a screenshot:
![index](https://cloud.githubusercontent.com/assets/5238955/4876645/28eb5530-62cd-11e4-9bfa-892fb95099b2.png)

The funny thing is that they are only rendered bad when they are received.

**Comment by TitanNano** [comment] 2014-11-06 18:09
Which version of the app are you using? as far as I know, this should be fixed already.

**Comment by gargsms** [comment] 2014-11-06 18:12
0.3.4a

I am using the latest pull from this repo, with #547 applied.

**Comment by TitanNano** [comment] 2014-11-06 18:15
okay, then this is a new issues, I just know that a similar problem already got fixed. I assume that the fix only applies to a part of the broken emojis.

**Comment by gargsms** [comment] 2014-11-06 18:17
@TitanNano Fix issue number?

**Comment by TitanNano** [comment] 2014-11-06 18:25
this was commit cad1832 for #488

**Comment by gargsms** [comment] 2014-11-06 18:33
I guess a similar patch follows. The entries to be modified are:

https://github.com/loqui/im/blob/dev/src/scripts/loqui/connectors/coseme.js#L1250
https://github.com/loqui/im/blob/dev/src/scripts/loqui/connectors/coseme.js#L1308

1f52b is the gun. :stuck_out_tongue: 
Anyway, why is this repo inactive for about a month now? Where did everyone go?

**Comment by TitanNano** [comment] 2014-11-06 18:36
that's a good question. @aesedepece is the repo owner and he hasn't be here since 6 October I think...

**Comment by aesedepece** [comment] 2014-11-07 08:01
I'm sorry I've been out for a long time for personal reasons. Let's make up for lost time!

@TitanNano is right, this is duplicate of #488

**Closed as completed by aesedepece** 2014-11-07 08:01 UTC
Labels: duplicate
