### ISSUE TITLE
[WhatsApp] false image reception

### ISSUE THREAD

**Issue by tibtab** [loqui/im#706] opened 2015-05-05 16:15 UTC
When somebody sent an image or an audio file in a whatsapp group, I recieve it every tenth minute again.

**Comment by TitanNano** [comment] 2015-05-05 16:17
did you restart your loqui application? it never stops?

2015-05-05 18:15 GMT+02:00 tibtab notifications@github.com:

**Comment by tibtab** [comment] 2015-05-05 16:25
yes, I also restarted the phone. Nothing helps
could, belong to another problem I have. When the app is opened and the screen wents out, whatsapp stops the connection so the check is turnig yellow.

**Comment by TitanNano** [comment] 2015-05-05 16:27
do you use mobile data connection or just wifi?

2015-05-05 18:25 GMT+02:00 tibtab notifications@github.com:

**Comment by tibtab** [comment] 2015-05-05 16:31
just wifi

**Comment by TitanNano** [comment] 2015-05-05 16:34
which os version are you on? until v2.2 there is wifi sleep which is always
on. your phone turns off the wifi when it goes into stand-by.

2015-05-05 18:31 GMT+02:00 tibtab notifications@github.com:

**Comment by tibtab** [comment] 2015-05-05 16:35
i'm using v1.3

**Comment by TitanNano** [comment] 2015-05-05 16:37
I'm sorry. we can't fix that. I still wonder why you receive the files over
and over again.... when did this issue occur the first time?

2015-05-05 18:35 GMT+02:00 tibtab notifications@github.com:

**Comment by tibtab** [comment] 2015-05-05 16:40
it is there since I'm using v0.4.2b

**Comment by TitanNano** [comment] 2015-05-05 16:45
hmm okay I will see if I can reproduce it when I receive a pic in a group
again... how about single user chat? same problem?

2015-05-05 18:40 GMT+02:00 tibtab notifications@github.com:

**Comment by ghost** [comment] 2015-05-05 21:52
When on wifi, i also receive pictures everytime loqui reconnects. FxOS1.3

**Comment by TitanNano** [comment] 2015-05-05 21:56
I see. is any one able to provide me logs around the time you receive a
picture?

2015-05-05 23:52 GMT+02:00 JayVii notifications@github.com:

**Comment by ghost** [comment] 2015-05-06 12:12
I also could repeat that behavior on Firefox OS v2.0 within a group but not within single chats.

But i have no luck to record some logs maybe because there is not sleep mode of the wifi connection when connected to WebIDE.

e.g. I received a picture 6 times

**Comment by TitanNano** [comment] 2015-05-06 12:17
@bdcomp yes thats right. there is no sleep while you're phone is plugged. So it's related to wifi sleep?

**Comment by ghost** [comment] 2015-05-06 12:53
@TitanNano I am not sure, it try to do some more tests to reproduce the issue, maybe i could log something relevant

**Comment by gargsms** [comment] 2015-05-06 14:13
@TitanNano @bdcomp As far as I have observed, the issue is only with group chats, right.
And it is not just for Wi-Fi sleep. When I drop connection and reconnect on mobile data, I receive attachments again.
AFAIK this only happens when the attachment is not downloaded on the device. If you download the attachment, this corrects (mostly). So I believe it is related to the way ACK are handled in Loqui.

**Comment by TitanNano** [comment] 2015-05-06 14:48
ah I see. so to reproduce it, we need to get a pic in group chat, check
which ack is send, disconnect, reconnect check if the image will be
received again, download the image, reconnect again and see if we still
receive the file.

Is anyone able to do this and provide a log?

2015-05-06 16:13 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by ghost** [comment] 2015-05-06 18:12
I could reproduce it again. Connected to Wifi and WebIDE. Just received 4 picture in a group. Disconnect Loqui and connect it again. On every connect i receive the 4 pictures again.

Is there a easy way to anonymize the log file? I don't want to publish all my contacts to the net.

Or which part of the log could be interesting for that issue?

**Comment by TitanNano** [comment] 2015-05-06 18:16
first save the unanonymized log. then you can try to replace the from attribute from the message nodes. Use any text editor that supports search & replace.

**Comment by TitanNano** [comment] 2015-05-06 18:18
well interesting are the parts around the receiving of the message, sending of the corresponding ack and the image download and every other ack...

**Comment by ghost** [comment] 2015-05-06 18:57
I removed everything that maybe should not be public, if there is something else that should be removed please let me know. Also if i removed to much.

```
\d+@s\.whatsapp\.net  replaced by  xxxxxxxxxxxx@s.whatsapp.net
\"hexdata\"\:\"\w+\"  replaced by  "hexdata":"xxxxxxxxxxxx"
\"from\"\:\"\d+\-\d+@g.us"  replaced by  "from":"xxxxxxxxxxxx@g.us"
group\ id=\"\d+\-\d+\"  replaced by  group id="xxxxxxxxxxxx"
and some id stuff with xxxx
```

http://pastebin.com/22gfLmnt

**Comment by TitanNano** [comment] 2015-05-06 19:24
where can I get the other parts? ^^

**Comment by ghost** [comment] 2015-05-06 19:30
I think they show the same. The Log should show everything from connect to disconnect and the other logs, too

**Comment by TitanNano** [comment] 2015-05-06 19:46
oh yes my fault. 
So, your log shows that you receive the pictures and loqui sends the acknowledgments. Afterwards you disconnect. This is how it should be....

**Comment by tibtab** [comment] 2015-05-06 21:14
This also happend, when i dowloaded the files.

**Comment by 03927e9c** [comment] 2015-05-08 14:30
I have the same problem, so I tried several things. First I exited from two of the groups that keep sending me over and over the files, so then I could ask the admin to invite me again and see if that fixes the problem.... well no. I re-join the group and I keep recieving files. Also, when I was out of the group, it kept sending me files, here's a screenshot:
![pantallazo-ventana sin titulo-2](https://cloud.githubusercontent.com/assets/9679446/7538302/43493b82-f575-11e4-8597-d90949b59be1.png)

I have Firefox OS simulator, so I deleted it from the Firefox addons, restarted Firefox, then install Firefox OS simulator again (2.0), but that didn't work either.

**Comment by TitanNano** [comment] 2015-05-08 17:55
I'm also getting some pictures now... but still don't know what WhatsApp
expects from us....

2015-05-08 16:30 GMT+02:00 03927e9c notifications@github.com:

**Comment by gargsms** [comment] 2015-05-08 18:55
I am not very sure if that is the correct behaviour of XMPP servers, but shouldn't WhatsApp servers just delete any files after they are pushed on the device?

That aside, I can think of a brute-force approach to solve this.
As I understood from the logs, every incoming file SHOULD have an unique filehash with it. We can try to store the filehash'es received for the chat, and whenever the server tries to push the same filehash, we simply reject it. I am not very sure of the feasibility of this approach, though.
I will try reproducing this tomorrow and studying the logs.

**Comment by TitanNano** [comment] 2015-05-08 20:55
well the thing about storing the file hashes, if we get a lot of
filehashes our message receiving process will become slow...

what I saw was that the message nodes for the media messages had some
retries and offline attributes. have these been there before?

2015-05-08 20:55 GMT+02:00 Sukant Garg notifications@github.com:

**Comment by 03927e9c** [comment] 2015-05-11 22:55
Any updates on this?

**Comment by TitanNano** [comment] 2015-05-12 08:38
no sorry. I need to receive new pictures. But this issue has our attention.

**Comment by 03927e9c** [comment] 2015-05-18 04:40
It seems that after a while it stops... until someone sends another file.

**Comment by TitanNano** [comment] 2015-05-18 07:25
yes. I'm not sure yet. But as far as I know, group participants now send their acknowledgment to the sender of the group message. For the files it seems that there are 3 or 4 tries before whatsapp stops sending the picture.

**Comment by gargsms** [comment] 2015-05-19 16:03
I have reportedly received the same set of 6 images more than 20 times when I dropped connections over mobile data.

Since I was fed up of all the bugging, I muted the chat. That still bugged, so I cleared the chats. After clearing, I had to restart Loqui otherwise the chats just remain there. I got the same images about 3 - 4 times again. I cleared the chat maybe 2 more times and now I am living a peaceful life.

If others of you don't have important chats, try clearing them again and again till the issues disappears.
Let's hope this gets fixed soon.

I am so sorry I cannot devote any time to Loqui for a long time now. :sad:

**Comment by TitanNano** [comment] 2015-05-19 16:40
Today I talked with some whatsapp for android users:
I the latest version of WhatsApp group participants send their receive acknowledgment to the sender of the message and the sender also receives all the acknowledgments. This way whatsapp now marks group messages when every participant has received the message. I will try to implement this as soon as possible.

**Comment by tibtab** [comment] 2015-06-07 16:26
Any news on this?

**Comment by TitanNano** [comment] 2015-06-07 16:29
yes, do you still experience it?

**Comment by tibtab** [comment] 2015-06-07 16:37
yes, every few minutes

**Comment by TitanNano** [comment] 2015-06-07 16:42
okay, I think I have a fix for this then. I tried around a little and it is fine for me now.

**Closed as completed** 2015-06-09 10:48 UTC
Labels: bug, P1

**Comment by TitanNano** [comment] 2015-06-16 12:26
did anyone test the patch?

**Comment by tibtab** [comment] 2015-06-16 14:58
Yeah it works :)

**Comment by 03927e9c** [comment] 2015-06-18 22:27
Please push this to market place!

**Comment by 03927e9c** [comment] 2015-06-26 20:43
WTF!!!! why this fix isn't on Market Place???? it's so annoying!!!!

**Comment by TitanNano** [comment] 2015-06-27 07:31
@aesedepece needs to create a new version.
