### ISSUE TITLE
[Facebook]Cannot sign in to Facebook on FirefoxOS 2.6.0.0-prerelease

### ISSUE THREAD

**Issue by siddhartharao17** [loqui/im#936] opened 2016-01-29 07:11 UTC
Even with the correct login credentials, unable to sign in to facebook. 
whats app is configured only in 1 device.
![2016-01-29-12-40-03](https://cloud.githubusercontent.com/assets/8169998/12669327/a14b2a1a-c685-11e5-8ec2-c0d005258616.png)

**Comment by siddhartharao17** [comment] 2016-01-29 07:12
PS: whats app is configured only in 1 device.

**Comment by cmeerw** [comment] 2016-01-31 00:09
duplicate of #700

**Closed as completed by cmeerw** 2016-01-31 00:09 UTC
