### ISSUE TITLE
setting up xmpp/jabber

### ISSUE THREAD

**Issue by achintangal** [loqui/im#191] opened 2014-01-07 20:51 UTC
I keep seeing the "sychronizing" screen when I try to setup up my xmpp account. 
Btw, I am running firefox 1.1 and the xmpp account is with riseup.  I wll try to see if it works with google-talk.

**Comment by aesedepece** [comment] 2014-01-18 20:30
Duplicate of #181

**Closed as completed by aesedepece** 2014-01-18 20:30 UTC
Labels: duplicate, unconfirmed
