### ISSUE TITLE
[XMPP] Can't use jabber

### ISSUE THREAD

**Issue by moritzbuhl** [loqui/im#591] opened 2014-11-25 14:16 UTC
I type in username and password and press the login button and after logging in and synchronizing I am not logged in anymore. The account is not listed.
![2014-11-25-15-04-21](https://cloud.githubusercontent.com/assets/5376102/5184136/1208bc5a-74b5-11e4-8f47-ac6a832a3306.png)
![2014-11-25-15-04-26](https://cloud.githubusercontent.com/assets/5376102/5184138/14bb5386-74b5-11e4-9260-42e8d9534c54.png)
Console:

```
    RECV,,<body xmlns='http://jabber.org/protocol/httpbind'><iq id='_session_auth_2' type='result' to='pasta@jabber.de/Loqui' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'/></body>
    Connected
    SENT,,<presence xmlns='jabber:client'><status>Using Loqui IM on FirefoxOS</status><priority>96</priority><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://loqui.im' ver='TvFoFiq8Bwp2KA6I98H1ng4CUAY=='/></presence>
    SENT,pasta@jabber.de,<iq type='get' id='3258:roster' xmlns='jabber:client'><query xmlns='jabber:iq:roster' ver=''/></iq>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><iq id='disco' type='get' to='pasta@jabber.de/Loqui' from='pasta@jabber.de' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><query xmlns='http://jabber.org/protocol/disco#info'/></iq></body>
    SENT,pasta@jabber.de,<iq type='result' id='disco' xmlns='jabber:client' to='pasta@jabber.de'><query xmlns='http://jabber.org/protocol/disco#info'><identity category='client' type='phone' name='http://loqui.im'/><feature var='http://jabber.org/protocol/caps'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='urn:xmpp:attention:0'/><feature var='http://jabber.org/protocol/chatstates'/><feature var='urn:xmpp:delay'/><feature var='undefined'/><feature var='vcard-temp'/><feature var='urn:xmpp:receipts'/></query></iq>
    SENT,pasta@jabber.de,<iq type='result' id='disco' xmlns='jabber:client' to='pasta@jabber.de'><query xmlns='http://jabber.org/protocol/disco#info'><identity category='client' type='phone' name='http://loqui.im'/><feature var='http://jabber.org/protocol/caps'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='urn:xmpp:attention:0'/><feature var='http://jabber.org/protocol/chatstates'/><feature var='urn:xmpp:delay'/><feature var='undefined'/><feature var='vcard-temp'/><feature var='urn:xmpp:receipts'/></query></iq>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><presence from='pasta@jabber.de/Loqui' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><status>Using Loqui IM on FirefoxOS</status><priority>96</priority><c hash='sha-1' ver='TvFoFiq8Bwp2KA6I98H1ng4CUAY==' node='http://loqui.im' xmlns='http://jabber.org/protocol/caps'/></presence></body>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><presence to='pasta@jabber.de/Loqui' from='kaffeebohne@jabber.de/8.1' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><priority>1</priority><c hash='sha-1' ver='I22W7CegORwdbnu0ZiQwGpxr0Go=' node='http://pidgin.im/' xmlns='http://jabber.org/protocol/caps'/><x xmlns='vcard-temp:x:update'><photo>d3182313db9731107014bdff20afb71a0c55bfa6</photo></x><delay from='jabber.de' stamp='2014-11-25T13:45:52Z' xmlns='urn:xmpp:delay'/></presence></body>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><iq id='3258:roster' type='result' to='pasta@jabber.de/Loqui' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><query ver='5' xmlns='jabber:iq:roster'><item jid='kaffeebohne@jabber.de' subscription='both'/></query></iq></body>
    SENT,pasta@jabber.de,<iq type='get' from='pasta@jabber.de/Loqui' xmlns='jabber:client' id='3259:sendIQ'><vCard xmlns='vcard-temp'/></iq>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><iq id='purple525f5fa9' type='get' to='pasta@jabber.de/Loqui' from='kaffeebohne@jabber.de/8.1' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><query node='http://loqui.im#TvFoFiq8Bwp2KA6I98H1ng4CUAY==' xmlns='http://jabber.org/protocol/disco#info'/></iq></body>
    SENT,pasta@jabber.de,<iq type='result' id='purple525f5fa9' xmlns='jabber:client' to='kaffeebohne@jabber.de/8.1'><query xmlns='http://jabber.org/protocol/disco#info' node='http://loqui.im#TvFoFiq8Bwp2KA6I98H1ng4CUAY=='><identity category='client' type='phone' name='http://loqui.im'/><feature var='http://jabber.org/protocol/caps'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='urn:xmpp:attention:0'/><feature var='http://jabber.org/protocol/chatstates'/><feature var='urn:xmpp:delay'/><feature var='undefined'/><feature var='vcard-temp'/><feature var='urn:xmpp:receipts'/></query></iq>
    SENT,pasta@jabber.de,<iq type='result' id='purple525f5fa9' xmlns='jabber:client' to='kaffeebohne@jabber.de/8.1'><query xmlns='http://jabber.org/protocol/disco#info' node='http://loqui.im#TvFoFiq8Bwp2KA6I98H1ng4CUAY=='><identity category='client' type='phone' name='http://loqui.im'/><feature var='http://jabber.org/protocol/caps'/><feature var='http://jabber.org/protocol/disco#info'/><feature var='http://jabber.org/protocol/disco#items'/><feature var='urn:xmpp:attention:0'/><feature var='http://jabber.org/protocol/chatstates'/><feature var='urn:xmpp:delay'/><feature var='undefined'/><feature var='vcard-temp'/><feature var='urn:xmpp:receipts'/></query></iq>
    RECV,pasta@jabber.de,<body xmlns='http://jabber.org/protocol/httpbind'><iq id='3259:sendIQ' type='error' to='pasta@jabber.de/Loqui' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xmlns='jabber:client'><error type='cancel'><item-not-found xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq></body>
```

**Comment by codedust** [comment] 2014-12-10 18:08
I can confirm that I have the same issue on Firefox OS 2.1 using Loqui 0.3.4a.

**Comment by TitanNano** [comment] 2014-12-13 13:55
This is a duplicate of #606 and that seems more descriptive to me. I'll close this bug, look at #606 for future discussing.

**Comment by codedust** [comment] 2014-12-13 16:38
Creating a vCard in Pidgin solved it for me (although this should obviously not be the "patch").
Thanks!

**Comment by TitanNano** [comment] 2014-12-13 17:04
Yes I did the same. We really need a fix for this.

**Comment by aesedepece** [comment] 2015-02-08 13:55
Duplicate of #459

**Closed as completed by aesedepece** 2015-02-08 13:56 UTC
Labels: bug, duplicate
