### ISSUE TITLE
Support OpenPGP (or something else) for for offline messages

### ISSUE THREAD

**Issue by tt123456** [loqui/im#661] opened 2015-03-23 13:09 UTC
At the moment there is no way to send end-to-end encrypted offline messages. So it would be nice if loqui would fall back to a method for offline end-to-end encryption when the recipient is not online.

At the moment OpenPGP seems to be the best option (although it was obsoleted by the XMPP Council) because it supports offline messages and multiple resources(necessary if the recipient goes offline and comes online later with a different resource): 

Comparison of end-to-end encryption mechanisms:
http://wiki.xmpp.org/web/XMPP_E2E_Security#Comparative_Overview

**Comment by TitanNano** [comment] 2015-03-25 11:50
kind of a duplicate of #659

**Closed as completed by TitanNano** 2015-03-25 11:50 UTC
Labels: duplicate
