### ISSUE TITLE
[WhatsApp] Authentication failed

### ISSUE THREAD

**Issue by janu2015** [loqui/im#982] opened 2016-03-22 20:22 UTC
Hi there,

anyone else facing a authentication error since today 19:54 CET?
Here's some logging from WebIDE:

`19:54:53.855 keep alive! tools.js:17
19:54:53.856 Write node called with  null ~ self._writeNode@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:7777:7 [ConnectionManager] tools.js:17
19:54:55.833 Error writing! {"data":"{}"} ~ self._onErrorSendDisconnected@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:7788:9 [ConnectionManager] tools.js:17
19:54:57.926 init tools.js:17
19:54:57.932 auth_login called for 49XXXXXXX ~ methodList.auth_login@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:8171:9 [ConnectionManager] tools.js:17
19:54:57.934 Connecting to: c2.whatsapp.net:443 ~ openConnection@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6293:5 [auth] tools.js:17
19:54:58.700 Starting login... ~ tryLogin@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6309:5 [auth] tools.js:17
19:54:58.701 Sending stream start, features & authentication ~ tryLogin@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6314:5 [auth] tools.js:17
19:54:58.713 <stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>
 ~ BinaryWriter.prototype._write@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:4835:7 [BinaryWriter] tools.js:17
19:54:58.715 There is a existing challenge, trying one-shot auth! ~ getAuth@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6475:7 [auth] tools.js:17
19:54:58.717 nonce (latin1): ;ýÙPÝ¡öLXXX8q²o´D? ~ KeyStream.getKeys@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6534:7 [KeyStream] tools.js:17
19:54:58.717 password (base64): XXXSYuXnlM7cV6IvJB0L963hl58= ~ KeyStream.getKeys@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6535:7 [KeyStream] tools.js:17
19:54:58.748 Keys: {"outputKey":{"$super":{"$super":{}},"words":[-912616483,711667718,-916116039,-XXXXXX],"sigBytes":20},"outputHMAC":{"$super":{"$super":{}},"words":[-1290552354,-122267820,1400798160,XXXXXX],"sigBytes":20},"inputKey":{"$super":{"$super":{}},"words":[-1505589814,-1686154391,187566639,-XXXXXXX],"sigBytes":20},"inputHMAC":{"$super":{"$super":{}},"words":[638697457,494932674,-991880544,XXXXXX],"sigBytes":20}} ~ KeyStream.getKeys@app://8eb503f6-951d-41a3-adb5-2e8f398bd76e/scripts/mozillahispano/coseme.js:6555:7 [KeyStream] tools.js:17
19:54:58.768 <auth mechanism="WAUTH-2" user="49XXXXXX">
XXXXÐ}Et(_2ö]þÃa¶`B~ÁcÈ*Oíù¨#¸&ëÞv{Yú?ôýÇH@~IM¬u¢?Äün?$Gb?-L9?ÖÝ¾ìç×3æhÝÇ?LUQÿÓDei>ÆÄ×X%;üÌÞÐ#§4ÝXXXX`

Sorry for missing line breaks.

Thanks in advance
Janu

**Comment by tibtab** [comment] 2016-03-22 20:27
I'm experiencing the same

**Comment by YunitoMH** [comment] 2016-03-22 20:29
Me to, I'm just experiencing the same and OpenWapp doesn't work... So it's really annoying that I can't use Whatsapp.

P.S: Thanks tibtab to quote this issue

**Comment by cmeerw** [comment] 2016-03-22 21:38
Unfortunately, 0.5.0 is still in the review queue on the Marketplace...

Anyway, we can try pretending to be an iPhone - hope it doesn't cause too many side effects...

**Comment by janu2015** [comment] 2016-03-22 21:44
Hi cmeerw, it's me, Janu, from Camp Firefox forum.

As you know I'm using 0.5.0 (built from the latest sources) ...

**Comment by TitanNano** [comment] 2016-03-22 21:48
@janu2015 the problem is we can't identify as Android as long as the majority of the users still don't have encryption. But you should be able to connect again now.

**Comment by cmeerw** [comment] 2016-03-22 21:52
Well, it's all complicated... So far Loqui tried to pretend to be some S40 version that doesn't support encryption for group messages (that S40 version is no longer allowed to log in to WhatsApp). Newer versions of S40 will require encryption for group messages - this is still not supported by 0.5.0, but 0.5.0 has slightly better error handling for encrypted group messages. Anyway, I have now updated the resource string to an iPhone version that doesn't support encryption for group messages, so should be similar to the S40 resource we were using.

Your Loqui should be able to connect again within an hour... (as it tries to update the tokenData when it gets an authentication failure)

**Comment by YunitoMH** [comment] 2016-03-22 21:54
cmerw: I'm using the version that is on Marketplace, will it work too?

**Comment by cmeerw** [comment] 2016-03-22 21:56
@YunitoMH yes, it should work as before within the next hour (the tokenData update logic is already in the marketplace version).

**Comment by Honk2** [comment] 2016-03-22 22:15
It is working again! Thank you!

**Comment by YunitoMH** [comment] 2016-03-22 22:26
Yeah it's working again but a with strange behaviour.. I mean, I recieve all messages 3 or 4 times and I'm not sure if the groups recieve my messages.

Edit: @cmeerw I can't get new messages or sent them, so I think it wasn't a good idea to change it to Iphone.

Edit2: I talked with my contacts, and they get my messages but I can't their messages.

**Comment by cmeerw** [comment] 2016-03-22 22:36
@YunitoMH do you have any logs?

**Comment by YunitoMH** [comment] 2016-03-22 22:44
@cmeerw Sadly, I can't get them because some months ago I don't know what I did but my OS doesn't recognize it. I will have to re-install the SO. But, to sum up, I get the same messages all the time and they can read what I send, but I don't get new messages.

**Comment by cmeerw** [comment] 2016-03-22 23:09
Ok, I think I can see the problem... BTW, this also happens with newer S40 versions...

**Comment by YunitoMH** [comment] 2016-03-22 23:10
I hope you can solve it, you seem really interested and energetic about solving it, I like it!

**Comment by cmeerw** [comment] 2016-03-22 23:45
Ok, I believe I have fixed the group message issue now...

**Comment by YunitoMH** [comment] 2016-03-23 11:55
@cmeerw I'm sorry but.. The behavior is still happening

**Comment by tibtab** [comment] 2016-03-23 12:02
@YunitoMH you'll have to build the newest version that it works. https://github.com/loqui/im/wiki/Build-Loqui

**Comment by YunitoMH** [comment] 2016-03-23 16:40
Done! And..The problem is there yet

**Comment by cmeerw** [comment] 2016-03-23 17:50
@YunitoMH What exactly did you do?

**Comment by YunitoMH** [comment] 2016-03-23 18:32
I built it from Git

**Comment by cmeerw** [comment] 2016-03-23 18:37
Do you have log files then?

**Comment by Honk2** [comment] 2016-03-23 19:52
I build 5.1 and it works for me.

**Comment by YunitoMH** [comment] 2016-03-23 20:05
I have t'he 0.5

**Comment by YunitoMH** [comment] 2016-03-23 21:24
I have just built 5.1 and the problem is the same. 

@cmeerw: I have a log but I think is useless:

`[l10n] #contactAdd is undefined. 
    at consoleWarn (app://227f20f9-f9df-4453-bb89-1ed4217ed3f9/scripts/fabi1cazenave/l10n.js:68:7) l10n.js:68:7
pre-main prep time: 6 ms curve25519.js:1:2750
Successfully compiled asm.js code (loaded from cache in 455ms) curve25519.js
String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead`

**Comment by janu2015** [comment] 2016-03-23 21:42
Still facing strange behavior using group chats: At some time the messages are processed in real-time (send and receive) and at some time they are delayed for more than an hour (still waiting for messages that were sent 90 minutes ago). Some messages are (received and) displayed a couple of times, even images.
Also, the time display between messages is missing, even if the gap is longer than one minute.

I have some logs, copied from WebIDE console. Unfortunately they're truncated due to binary characters. I will attach one.

By the way, yesterday I configured Loqui IM to write log files, but today's and yesterday's logs are empty: loqui/logs/2016-03-23.log

**Comment by cmeerw** [comment] 2016-03-23 21:42
Can you go to Settings and then enable both "Developer mode" and then
"Debug mode" to get more useful log output.

**Comment by janu2015** [comment] 2016-03-23 21:45
[loqui_20160323-205509.txt](https://github.com/loqui/im/files/186919/loqui_20160323-205509.txt)

Edit: Some (maybe all) of the missing messages were just received, about 50 in a row, texts and images (each image nine or ten times). 
Unfortunately I'm not connected to WebIDE ...

Edit2: I'm sorry about closing / opening the issue, I picked the wrong button ...

Edit3: I made a screenshot of Loqui dev console.
![2016-03-23-22-54-38x](https://cloud.githubusercontent.com/assets/18015036/14002461/767ffa4e-f14c-11e5-9875-d49b66f1ca96.png)

**Comment by YunitoMH** [comment] 2016-03-23 22:00
I enabled both Developer Modes and it's the same but a bit better.

`'TypeError: setting a property that has only a getter
 dsa-webworker.js:7:5
unreachable code after return statement coseme.js:7140:10
unreachable code after return statement coseme.js:7151:10
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:4
[l10n] #contactAdd is undefined. l10n.js:68:7
pre-main prep time: 8 ms curve25519.js:1:2750
Successfully compiled asm.js code (loaded from cache in 747ms) curve25519.js
String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead'`

What do you think @cmeerw

**Comment by janu2015** [comment] 2016-03-24 23:23
@cmeerw tonight I recorded a new log containing an error. Yet, I'm not sure whether it's useful solving this issue ...

Some group chat messages seem to be received in real-time (22:02 - 22:14). 
The ping at 22:58:17.731 has not being responded. Instead a stream:error appeared 29 seconds later.
Logging stopped then for a couple of minutes, except for the SET NEW ALARM messages.
At that time Loqui was not responding to (every) touch gesture (leaving / entering group chat). Maybe I was able to wipe from the left and enter &lt;aside id="accounts"&gt; then, not sure.

Some more statistics:
There's a ping every 3:02 or 3:03 minutes
SET NEW ALARM is logged every 1:30 or 1:31
keep alive! is logged every minute

[loqui_20160324-230607zzz.txt](https://github.com/loqui/im/files/188796/loqui_20160324-230607zzz.txt)

**Comment by cmeerw** [comment] 2016-03-24 23:53
@janu2015 that's weird... If you are adventurous you could try setting the resource string to 'S40-2.13.30' (CoSeMe.config.tokenData.r = 'S40-2.13.30' and then reconnect) and see what happens (although that could lead to receiving encrypted group messages which are not supported)...

**Comment by cmeerw** [comment] 2016-03-24 23:54
@YunitoMH you should see much more detailed logs when enabling "Debug mode"

**Comment by janu2015** [comment] 2016-03-25 22:33
@cmeerw Of course I'm not adventurous. Otherwise I would use an exotic smartphone OS like Android or iOS ;-)

Today some group messages were received. So, yesterday's issue appeared temporarily only. But still (some) messages are received (or displayed) delayed.

**Comment by YunitoMH** [comment] 2016-04-04 04:48
Same here, I send some messages, and I receive some. But today it seems that I can send them but not receive them

**Comment by cmeerw** [comment] 2016-04-04 05:36
So does anything appear in the logs?

**Comment by Zeus76** [comment] 2016-04-04 22:24
Hello:
I get the "authentication error" screen.
![blob](https://cloud.githubusercontent.com/assets/15674458/14265916/aa23ae96-fac4-11e5-94bc-3d85eb1efd41.png)

**Comment by cmeerw** [comment] 2016-04-05 05:38
I have updated the version we use to connect. Unfortunately, this will enable encrypted group messages which we don't support yet, so some group messages might get lost...

**Comment by janu2015** [comment] 2016-04-05 07:02
Thanks, but I updated and built Loqui, and authentication still fails.

**Comment by cmeerw** [comment] 2016-04-05 07:12
@janu2015 that's interesting - I can connect with the marketplace version...

What do you get for "CoSeMe.config.tokenData.r" in the Javascript console? Maybe it's still using the old version...

**Comment by Zeus76** [comment] 2016-04-05 08:07
The application already works for me.

**Comment by janu2015** [comment] 2016-04-05 09:11
I will check at Feierabend.

**Comment by YunitoMH** [comment] 2016-04-05 11:09
For me, it stopped working and I can't receive my contacts messages, I'll try updating it

**Comment by YunitoMH** [comment] 2016-04-05 11:12
I have version 0.5.2, I think the last one

**Comment by cmeerw** [comment] 2016-04-05 11:19
@YunitoMH what does "stopped working" mean, what does "can't receive my contacts messages" mean?

Could you all please provide logs, otherwise it's just guessing...

**Comment by YunitoMH** [comment] 2016-04-05 11:48
Exactly,  I can receive group messages but I can't receive contacs messages. When I got home, I'll try to get some

**Comment by YunitoMH** [comment] 2016-04-05 14:19
Exactly, I can receive group messages but I can't receive contacs messages.

@cmeerw: Here is the log, I can't get anything more

`TypeError: setting a property that has only a getter
<anonymous>
 dsa-webworker.js:7
<anonymous>
 dsa-webworker.js:1
 dsa-webworker.js:7:5
unreachable code after return statement coseme.js:7140:10
unreachable code after return statement coseme.js:7151:10
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:4
[l10n] #contactAdd is undefined. l10n.js:68:7
pre-main prep time: 6 ms curve25519.js:1:2750
Successfully compiled asm.js code (loaded from cache in 1024ms) curve25519.js
String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead coseme.js:7233:9
Error: Illegal group end indicator for Message .com.whatsapp.proto.Message: 435414991 (not a group)`

`CoSeMe.config.tokenData.r
"S40-2.13.30"`

I hope this is useful enough

**Comment by cmeerw** [comment] 2016-04-05 14:28
Please enable "Developer Mode" and then "Debug Mode" to get proper logs.

**Comment by YunitoMH** [comment] 2016-04-05 14:43
@cmeerw: I have it enabled, "Developer Mode" and "Debug Mode with ADB and Devtools" and I only get:

`TypeError: setting a property that has only a getter
 dsa-webworker.js:7:5
unreachable code after return statement coseme.js:7140:10
unreachable code after return statement coseme.js:7151:10
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:4
[l10n] #contactAdd is undefined. l10n.js:68:7
pre-main prep time: 10 ms curve25519.js:1:2750
Successfully compiled asm.js code (loaded from cache in 296ms) curve25519.js
String.prototype.contains() is deprecated and will be removed in a future release; use String.prototype.includes() instead coseme.js:7233:9
Error: Illegal wire type for unknown field 10 in Message .com.whatsapp.proto.Message#decode: 6 protobuf-light.min.js:48:376`

**Comment by cmeerw** [comment] 2016-04-05 14:47
"Debug mode" is in the Loqui Settings in the Developer tab.

**Comment by YunitoMH** [comment] 2016-04-05 15:04
Ah okay! Sorry! I was getting crazy =D. Let's try this time:

`TypeError: setting a property that has only a getter
 dsa-webworker.js:7:5
unreachable code after return statement coseme.js:7140:10
unreachable code after return statement coseme.js:7151:10
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ l10n.js:125:4
[l10n] #contactAdd is undefined. l10n.js:68:7
pre-main prep time: 6 ms curve25519.js:1:2750
Successfully compiled asm.js code (loaded from cache in 713ms) curve25519.js
SHOW main undefined undefined tools.js:17:7
init onsuccess tools.js:17:7
init tools.js:17:7
auth_login called for -- ~ methodList.auth_login@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:8172:9 [ConnectionManager] tools.js:17:7
Connecting to: c2.whatsapp.net:443 ~ openConnection@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6293:5 [auth] tools.js:17:7
REMOVE ALARM Object { id: 10062, date: Date 2016-04-05T14:55:40.435Z, respectTimezone: "ignoreTimezone", data: Object } tools.js:17:7
SET NEW ALARM 10063 tools.js:17:7
Starting login... ~ tryLogin@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6309:5 [auth] tools.js:17:7
Sending stream start, features & authentication ~ tryLogin@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6314:5 [auth] tools.js:17:7
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>
 ~ BinaryWriter.prototype._write@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:4835:20 [BinaryWriter] tools.js:17:7
There is a existing challenge, trying one-shot auth! ~ getAuth@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6475:7 [auth] tools.js:17:7
nonce (latin1): º}r
xx$ÖÈyG¶¾ 
ºÂ ~ KeyStream.getKeys@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6534:7 [KeyStream] tools.js:17:7
password (base64): P59xEKGR0A0k4RlYO5yVbMQ0Vnc= ~ KeyStream.getKeys@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6535:7 [KeyStream] tools.js:17:7
Keys: {"outputKey":{"$super":{"$super":{}},"words":[331823670,1959130959,1014464102,955586598,1263525321],"sigBytes":20},"outputHMAC":{"$super":{"$super":{}},"words":[953359109,-1951640072,1091890598,994083216,1554704835],"sigBytes":20},"inputKey":{"$super":{"$super":{}},"words":[180925900,-1575666348,-1801256784,1484857107,-232000423],"sigBytes":20},"inputHMAC":{"$super":{"$super":{}},"words":[1091918287,-589649284,293063217,-398615928,-1175764989],"sigBytes":20}} ~ KeyStream.getKeys@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6555:7 [KeyStream] tools.js:17:7
<auth mechanism="WAUTH-2" user="">
ï¼E+mI`;ÂÅw×G+tÞ:#÷l#HâVL#É@§6¨À#ã¼©p«×(¸ë¯wg#É#c.â/#
ó      +£#KèâÕ#TÁû 3#g2ÞCZ@ËÈâK#m±\¡@ÂÙ³Wò5ó×cÊH|¨;O¹#>Ó</auth>
 ~ BinaryWriter.prototype._write@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:4835:20 [BinaryWriter] tools.js:17:7
Waiting for stream start... ~ waitForAnswer@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:6348:5 [auth] tools.js:17:7
Received socket data: 78 bytes! ~ BinaryReader.prototype.onSocketData@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5273:5 [BinaryReader] tools.js:17:7
stream:features
/stream:features
 ~ BinaryReader.prototype._readNextTree@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5367:7 [BinaryReader] tools.js:17:7
<success t="1459868096" props="4" kind="free" status="active" creation="1349360277" expiration="4444444444">
r©U {Û©¢¯    $ÊXà</success>
 ~ BinaryReader.prototype._readNextTree@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5367:7 [BinaryReader] tools.js:17:7
Received socket data: 32 bytes! ~ BinaryReader.prototype.onSocketData@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5273:5 [BinaryReader] tools.js:17:7
<ib from="s.whatsapp.net">
<dirty type="groups" timestamp="1459868096">
</dirty>
</ib>
 ~ BinaryReader.prototype._readNextTree@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5367:7 [BinaryReader] tools.js:17:7
Received socket data: 435 bytes! ~ BinaryReader.prototype.onSocketData@app://29c48974-bef3-47ff-95fc-405c3916b9f7/scripts/mozillahispano/coseme.js:5273:5 [BinaryReader] tools.js:17:7
<message from="@s.whatsapp.net" type="text" id="B7B2B46BF25F92DA355AD2BCFF968B" offline="2" t="1459867604" notify="Carme">
<enc v="2" type="msg">
3
!#jcXu9îJñ>ÅøÊN#]±ùV#TðY#î##
xx$ÖÈyG¶¾ `

Edit: I deleted the phone numbers for privacy

**Comment by Zeus76** [comment] 2016-04-05 16:09
My messages never reach a recipient. This recipient Loqui use IM v0.5.2. It is discharged from the market. After a while it stops working.  In other recipients other messages arrive.
[No_llegan.txt](https://github.com/loqui/im/files/204857/No_llegan.txt)

**Comment by cmeerw** [comment] 2016-04-05 16:33
@YunitoMH that doesn't look like it's complete... is there anything being logged after that?

**Comment by YunitoMH** [comment] 2016-04-05 16:43
@cmeerw: No, that's all. I tried to run it again and everything ends there. The other things are numbers from my contacts

**Comment by janu2015** [comment] 2016-04-05 18:00
> @janu2015 that's interesting - I can connect with the marketplace version...
> 
> What do you get for "CoSeMe.config.tokenData.r" in the Javascript console? Maybe it's still using the old version...

@cmeerw Now it works,   for whatever reason ... I didn't touch it since this morning. TokenData is correct: "S40-2.13.30"
Fortunately, at least in one group chat messages are not encrypted.

Btw,  what's more difficult about processing encrypted group messages?

**Comment by cmeerw** [comment] 2016-04-05 20:08
@janu2015 it can take up to 2 hours for LoquiIM to update the tokenData. Group messages just use a different encryption protocol (and unfortunately not implemented in libaxolotl-javascript), so there is some work to do...

@YunitoMH there is no way the log ends in the middle of an "enc" tag... Anyway, I have checked in a change that might fix it. BTW, are you using the marketplace version or the github sources?

**Comment by YunitoMH** [comment] 2016-04-05 20:49
I'm using the Github source, why?

**Comment by janu2015** [comment] 2016-04-06 07:00
> @janu2015 it can take up to 2 hours for LoquiIM to update the tokenData. Group messages just use a different encryption protocol (and unfortunately not implemented in libaxolotl-javascript), so there is some work to do...

I see!

Regarding encrypted single chat messages, it seems that some messages of the same participant are being decrypted and some are not ...
There's a log attached containing an encrypted message: Decryption failed. 
Loqui does not inform about failed decryptions?
[2016-04-05_0.49ZZZ.log.txt](https://github.com/loqui/im/files/205893/2016-04-05_0.49ZZZ.log.txt)

**Comment by cmeerw** [comment] 2016-04-06 07:12
I don't see any decryption failure in that log. All I see is that
encrypted messages are received, but not decrypted (this might be
caused by an earlier failure that's not shown in the log).

**Comment by cmeerw** [comment] 2016-04-06 09:01
BTW, that problem might have been fixed yesterday evening - so please
recheck with the current version.

**Comment by YunitoMH** [comment] 2016-04-06 14:04
Still happens mmy error

**Comment by janu2015** [comment] 2016-04-06 19:34
> I don't see any decryption failure in that log. All I see is that encrypted messages are received, but not decrypted (this might be caused by an earlier failure that's not shown in the log).

What should I look for in the logs? There's no exception stack trace. I found other errors <error type="plaintext-only"> (see attachment, there's one participant in a group chat who sends encrypted, others don't yet) and <error code="404" text="item-not-found">.

Should I upgrade to the recent revision containing today's commits?

[2016-04-06_0.49YYY_49XXX.log.txt](https://github.com/loqui/im/files/207199/2016-04-06_0.49YYY_49XXX.log.txt)

**Comment by cmeerw** [comment] 2016-04-06 20:01
@janu2015 yes, please use the latest version. The most important things to look out for are Javascript exceptions (as these can then cause the decryption stuff to stop working - which I believe is what happen in your previous log, but the exception itself wasn't shown there). The "plaintext-only" just means that encryption is not supported for groups.

**Comment by janu2015** [comment] 2016-04-06 20:41
I just upgraded. 
I checked the logs. No JS exception appeared. My (encrypted) message to 49ZZZ was marked delivered and viewed (20:16:30) and the immediate (v2 encrypted) response could not be decrypted (20:16:35 and a second attempt 20:16:49). That's all ...

Btw, the plaintext of my encrypted messages is not logged?

**Comment by janu2015** [comment] 2016-04-09 22:05
@cmeerw I checked today's three loqui logs. I noticed a huge amount of "notify" messages (and traffic) related to a whatsapp group chat, up to 17 (!) per second. 
Meanwhile two of twelve members are chatting encrypted.

Search "error type="plaintext-only"" (1593 hits in 3 files)
Search "error type" (1593 hits in 3 files)

Search "notify="" (1573 hits in 3 files)
The "notify" entries are related to four group members: SSS (encrypts messages, group starter/admin), EEE (encrypts messages), DDD and TTT.

Sometimes the same (encrypted) message is sent again and yet again, sometimes they seem to be different (maybe whatsapp sends all messages of the participant again since he started encrypting as they have not been ACKed?).
I removed most of the log content, I leaved a few messages samples. At the beginning, at 14:26:49, at 17:09:57, at 20:49:38

I think I recognized this behaviour before v0.5.3. Maybe it appears more often now.

One media message was sent and received, not encrypted:
14:26:49 a media (image) message from DDD received, id="7E8CEA01F7AF678337"

Regarding the logging, it seems that it stops occasionally. There are leaps in time, e.g. at 17:09:57. Next entry is at 20:49:29. 
Also, I noticed that log file rotation fails sometimes. Sometimes at 1MB and sometimes even earlier, I feel. Instead it is truncated. 

[loqui_20160409_log_notify.txt](https://github.com/loqui/im/files/211498/loqui_20160409_log_notify.txt)

**Comment by Honk2** [comment] 2016-04-12 21:52
It happened again.
Starting UTC 21:30 authentification fails..

**Comment by Honk2** [comment] 2016-04-12 22:17
And is working again. Wow @cmeerw , thank you.

**Comment by janu2015** [comment] 2016-04-13 21:49
Yes, thanks @cmeerw. 
Where do you know the next token data from whenever an update is needed ("S40-2.13.30" --> "S40-2.13.39") ?

Also, logging works better now.  Yet, the log is truncated sometimes.

**Comment by 03927e9c** [comment] 2016-04-14 00:49
Can you please push it to MP? gosh

**Comment by cmeerw** [comment] 2016-04-14 05:16
Can you please find a marketplace reviewer and hold him hostage until
he approves the app.

**Comment by janu2015** [comment] 2016-04-17 19:44
This is another sample of strange group chat behaviour. Two topics: 
1. Since latest token data update, if an encrypted group chat message is received, usually it cannot be decrypted. A known issue, of course.  After this the log (8MB within 30mins) is full of hundreds of encrypted messages sent by the same participant (I reported this earlier).
2. Same group chat: participant KKK sent an encrypted message that also leads to "plaintext-only" error. One second later the (same?) message was sent as plaintext.
Hopefully the log attached may help solving the issue.
[2016-04-17_0.log.txt](https://github.com/loqui/im/files/222820/2016-04-17_0.log.txt)

**Comment by cmeerw** [comment] 2016-04-18 15:52
@janu2015 I don't see anything wrong with the 04-17 log - the "plaintext-only" error is the expected behaviour to ask the sender for a plaintext version of the message.

BTW, is your previous issue reproducible or was that a one-off behaviour?

**Comment by janu2015** [comment] 2016-04-18 20:42
> @janu2015 I don't see anything wrong with the 04-17 log - the "plaintext-only" error is the expected behaviour to ask the sender for a plaintext version of the message.

@cmeerw Thanks for explaining.

> BTW, is your previous issue reproducible or was that a one-off behaviour?

It happens nearly always an encrypted group chat message is received (for some time three group chat participants send encrypted messages). Loqui then subsequently receives hundreds of encrypted messages by the same participant. That's why I deactivate Loqui most of the time. Does it ask for a plaintext message for each encrypted message ever sent by the participants?
Today's analysis (~22 MB in 22 log files):
Search "notify="EEE" (1333 hits in 14 files)
Search "notify="SSS" (3137 hits in 20 files)
Search "notify="TTT" (1980 hits in 21 files)
There are rare exceptional cases: I remember one occurrence within the last few days of either one of them sent a plaintext message or Loqui was able to decrypt it.

**Comment by cmeerw** [comment] 2016-04-18 21:05
Hmm, ok so maybe some WhatsApp clients are now responding to a "plaintext-only" error by just resending the encrypted message again... (which seems rather pointless)

**Comment by cmeerw** [comment] 2016-04-21 06:02
closing, original problem has been fixed - anything else needs to be handled in separate issues (with proper problem description)

**Closed as completed by cmeerw** 2016-04-21 06:02 UTC
