### ISSUE TITLE
Implement import and export (backup and restore) options

### ISSUE THREAD

**Issue by bdcomp** [loqui/im#507] opened 2014-08-19 12:40 UTC
As per https://github.com/loqui/im/issues/496#issuecomment-52623490, the import and export options should be implemented.

WIP code: https://github.com/loqui/im/issues/496#issuecomment-52621539

**Comment by aesedepece** [comment] 2014-08-21 19:04
:+1:

**Comment by TitanNano** [comment] 2014-09-12 23:18
just a question: Would it be possible to implement the import and export of WhatsApp chat logs? Compatible with the official WhatsApp backup files so users are able to transfer their existing conversations from a phone with the official app?

**Comment by gargsms** [comment] 2014-10-04 07:27
https://github.com/loqui/im/issues/496#issuecomment-52621539

It so happens that my JSON.stringify(backup) string is too long to be logged properly. Also, I have no idea why window.print() does not work in the App Manager console. :disappointed: 

Anyway, I would like to implement the export and import features (I cannot lose my chats :p) 

@aesedepece Will indexedDB be a good approach for the same? Can we copy the sqlite stores and use them for backup purposes? Anything to get me started will be very much appreciated. Cheers!

**Comment by TitanNano** [comment] 2015-02-10 14:05
this is a duplicate of #190

**Closed as completed by TitanNano** 2015-02-10 14:05 UTC
Labels: JS
